### ISSUE TITLE
Add h5py to list of dependencies

### ISSUE THREAD

**Issue by emmanuelle** [tomopy/tomopy#158]
h5py is not mentioned in requirements.txt, yet it seems to be needed. I got an error when importing tomopy:
```
In [1]: import tomopy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-85799eefe1d1> in <module>()
----> 1 import tomopy

/home/emma/travail/projects/tomopy/tomopy/__init__.py in <module>()
     51 
     52 from tomopy.io import *
---> 53 from tomopy.io.exchange import *
     54 from tomopy.io.phantom import *
     55 from tomopy.io.reader import *

/home/emma/travail/projects/tomopy/tomopy/io/exchange.py in <module>()
     57 import os.path
     58 import re
---> 59 import h5py
     60 import tomopy.io.reader as tio
     61 import logging

ImportError: No module named h5py

```

**Comment by dgursoy** [comment]
Hi @emmanuelle, requirement.txt captures dependencies only for the documentation, and not the tomopy requirements. But I understand this is not intuitive and I think we have to explain it somewhere in the docs. If you just want to use the package without any modifications, I suggest you use Conda for a quick installation, since it takes care of all dependencies. But if you want to use manual install, then you can find all required packages in the Conda recipe, i.e. in meta.yaml sitting at root folder.

**Comment by emmanuelle** [comment]
Hi @dgursoy thanks for your quick answer.

I was actually trying to install tomopy "manually", with "python setup.py install", since conda usually messes with dependency in a way that is not always desired. I could install it without problems with apt-getting a few packages on my Ubuntu, it's just that on Python packages that I know, requirements.txt is usually something that is used in scripts for example for continuous integration.

**Comment by dgursoy** [comment]
With all the problems with pip install and requirements nightmare I faced in the past, I started using Conda even for continuous integration. But if you've already manually installed the packages, I'd be more than happy to accept your PR to update the current requirements.txt! Otherwise I can try to do that sometime soon.

**Comment by dgursoy** [comment]
Now all I/O functionality is shipped with ```dxchange``` package. We also have now ```requirements.txt``` for tomopy and ```requirements-doc.txt``` for docs dependencies.
