### ISSUE TITLE
Rotation Center

### ISSUE THREAD

**Issue by AoxiangGeng** [tomopy/tomopy#191]
Dear Tomopy team,

I am Aoxiang and currently working in Laboratoire de Réactivité et Chimie des Solides(LRCS), and now we are doing 3D image reconstruction with the help of Tomopy. 

The problem is when we want to find the rotation center using the function 'find_center' provided in tomopy/recon/rotation.py, there is always an error shows that : 
ZeroDivisionError in distribute_jobs
nchunk=(ndim-1)//ncore+1

Since it concerns with a lot of scripts so we don't know where to debug. Can you show me an example of how to use the find_center function? Or can you tell me where the bug is?

Thanks in advance!
Wish you all the best!

**Comment by dgursoy** [comment]
Hi @AoxiangGeng! Have you checked the shape of your data before you call ```find_center```? I suspect for some reason one of the dimensions could be zero.

An example code is here:
```
import tomopy
import dxchange

# desired center I want to find
mycen = 72

obj = tomopy.shepp3d(128)
ang = tomopy.angles(180)
prj = tomopy.project(obj, ang, center=mycen)
print (prj.shape)

cen = tomopy.find_center(prj, ang, tol=0.1)
print (cen)
```

**Comment by AoxiangGeng** [comment]
Hi Doga Gursoy,

Thanks a lot for your reply.

We tried to trim our script a little bit according to your example and got
some results,now we no longer has the zero dimension problem but these
results are quite unreasonable. It shows that the rotation center is
located at around 3000 but the dimension of our input data is just
1800*100*2560 in which the center should be around 1280. Below is the
script we used and the attachment is the raw CT image . Can you give us
more advice on where we can correct our script? Thanks a lot in advance.


Scripts:
import tomopy

# Initial Value guess
mycent=1280

# Provide file path of the data.
fname = '/home/Simon/Documents/Tomographie_Argonne/battery_9/proj_14.hdf'

# Read data provided by fname. prj is the projections.
# Selection of the sino range
prj, flat, dark = tomopy.read_aps_32id(fname,
                  sino=(550,650,1))

# ang is the array holding projection tilt angles.
# Selection of ang step between 2 images
ang = tomopy.angles(prj.shape[0])

# Perform flat/dark-field normalization.
# Make a blank with bright(flat) and dark images
prj = tomopy.normalize(prj, flat, dark)

# Perform ring removal (basically removes stripes from sinogram data).
# remove bright stop or ring
prj = tomopy.remove_stripe_fw(prj)

# Perform Pagannin phase retrieval.
# phase contrast by playing with alpha from 0 to 0.1
prj = tomopy.retrieve_phase(prj,
     dist=10,
     energy=31,
     pixel_size=1.3e-4,
     alpha=1e-3)


# Perform normalization based on background before reconstruction.
# normalization based on background
prj = tomopy.normalize_bg(prj)

# Find the rotation center
print prj.shape
cen= tomopy.find_center(prj, ang, emission=False,mask=True, init=mycent,
tol=0.1)
print(cen)





2016-04-14 23:05 GMT+02:00 Doga Gursoy <notifications@github.com>:

**Comment by tomopy** [comment]
Can you confirm the original file name of /proj_14.hdf
I cannot find it in our archive for /2016-03/Demortiere

thanks

francesco


________________________________

**Comment by AoxiangGeng** [comment]
Hi Doga,

We double checked the directory and it is correct. proj_14.hdf is the
original 3D tomographic data of battery number 9.

Also, we tried to use another function that tomopy provided to find the
rotation center. Its the find_center_vo and we get perfect results. So we
guess its perhaps because the method in find_center is not quite suitable
in our case.

Another important problem is about the installation of ASTRA. Our server
doesn't has a capable graphic card to install CUDA, so we want to know is
there any option that we can install and run ASTRA without CUDA?

Thanks a lot. Wish you all the best !
Aoxiang Geng

2016-04-19 22:49 GMT+02:00 tomopy <notifications@github.com>:

**Comment by tomopy** [comment]
ASTRA runs in nvidia GPUs and requires cuda. Which of the ASTRA methods you want to run? Some have the equivalent in the tomopy cpu implementation.

Sent by T-mobile

**Comment by dmpelt** [comment]
Just a small clarification: it is possible to install and run ASTRA without a GPU, also through TomoPy. Most reconstruction algorithms of ASTRA are supported on CPU as well, but of course will take much longer to compute compared with using a GPU. An overview of ASTRA's algorithms can be found [here](http://www.astra-toolbox.com/en/latest/docs/algs/index.html) (the 2D ones are relevant for usage through TomoPy).

Installation using conda is the same with or without a GPU (`conda install -c astra-toolbox astra-toolbox`). A small usage example of doing a CPU FBP reconstruction with ASTRA:

```python
rec = tomopy.recon(data, angles, 
    algorithm=tomopy.astra, options={'method':'FBP', 'proj_type':'line'})
```

**Comment by AoxiangGeng** [comment]
Thanks a lot for the answer about ASTRA ! SInce we are doing 3D reconstruction, installing CUDA seems to be mandatory. 

Still, we want to know what is wrong with the function ' find_center'.Because theoratically it should work.

**Comment by dmpelt** [comment]
In the case of using astra through tomopy, you would actually use the 2D algorithms of astra (i.e. slice-by-slice reconstructions) even if you perform a 3D reconstruction. So you should be able to run these without CUDA. Let me know (or create an issue on the astra toolbox github page) if you run into any problems!

**Comment by dmpelt** [comment]
To clarify: the 3D GPU-only algorithms mentioned in the astra documentation are used for more general tomography geometries (e.g. cone-beam, spiral-CT, etc), where slice-by-slice reconstructions are not possible. In the case of parallel-beam tomography, the 2D algorithms can be used for reconstructing the full 3D object slice by slice.

**Comment by AoxiangGeng** [comment]
Hi Dmpelt,

We just used :
rec = tomopy.recon(data, angles, 
    algorithm=tomopy.astra, options={'method':'FBP', 'proj_type':'line'})
and the other 2D CPU methods to reconsturct our images. But the return ndarray rec is all zeros. However, the result with the traditional method is quite ok: 
rec = tomopy.recon(data, angles, 
         center=my_cent, 
         algorithm='gridrec', 
         emission=False)
Any idea of what could be wrong here with ASTRA?

Thanks a lot !

**Comment by dmpelt** [comment]
Can you try  `import astra`  to see whether the astra toolbox is correctly installed? Since tomopy uses the `multiprocessing` module to distribute work over multiple processes, error messages like import errors are not reported, but will simply return an empty array.

**Comment by AoxiangGeng** [comment]
it shows that astra imported but unused, does that means astra is not installed correctly?

**Comment by AoxiangGeng** [comment]
But I double checked it , it is all installed:

[root@srvlrcs Desktop]# conda install -c astra-toolbox astra-toolbox
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /home/Simon/Softwares/anaconda2:
#
astra-toolbox             1.7.1               np110py27_0    astra-toolbox

**Comment by dgursoy** [comment]
Regarding centering: ```find_center``` may fail with noisy datasets. I think ```find_center_vo``` is more robust so I would recommend using that one. There is another algorithm that can give you a quick estimate, which is ```find_center_pc```. It only uses 0 and 180 degrees projection angles and calculates image correlation to obtain sub-pixel estimation of the rotation center.

**Comment by dmpelt** [comment]
Created a new issue (#195) for the ASTRA CPU issue, to prevent becoming too off-topic for the `find_center` issue here.

**Comment by rshopa** [comment]
I would like to ask the question related to 3D sinogram list mode. As I know, there should be at least 4 variables of each LOR - radial angle *fi*, displacement *s*, axial coordinate *z* and the angle between the LOR and the transaxial plane *theta* (see [D.L. Bailey et al, Positron Emission Tomography, Basic Science, Springer, 2005] ).

For the 3D projection created with tomopy.project() it's only 3 variables, one of which is projection angle, second corresponds to linear dimension of phantom and the **third is hard to understand** at all.
For the 128x128x128 image this 3rd parameter is of length 184 (close to sqrt(2)*128 = 181.2, but NOT EQUAL). 

I wonder what is the meaning of this third value?

I need to reconstruct an image from list of LORs denoted as two pairs of Cartesian coordinates - hit points at PET detectors - (x1,y1,z1) and (x2,y2,z2). Of course, it reflects tomograph geometry. 
How should I transform this data into 3D sinogram, say, **my_projection**, in order to use correctly tomopy.recon() function, in particular with Astra FBP implementation, i.e. 
```
ang = tomopy.angles(180)
...
options = {'proj_type':'linear', 'method':'FBP'}
recon = tomopy.recon(my_projection, ang, algorithm=tomopy.astra, options=options)
```

**Comment by dgursoy** [comment]
```project``` takes a 3D object and the rotation angles in radians, and computes a stack of 2D projections. With your definitions, the output volume is a 3D sinogram with dimensions (f, s, z). First dimension refers to the projections, and second and third dimensions provide the (s, z)-pixel in your 2D projection image.

I think what you are referring to as the third argument is the ```pad``` (correct?). If this value is ```False```, then it should provide you a 128x128x128 sinogram as you may have expected. If it is ```True```, it will provide you a 128x128x184 sinogram. The reason for that is as you explained, ```ceil(sqrt(128))=184``` is the minimum integer number for discrete array of pixels to compute the full projection array at the 45, 135, ... degrees (which is the diagonal of your object).

> I need to reconstruct an image from list of LORs denoted as two pairs of Cartesian coordinates - hit points at PET detectors - (x1,y1,z1) and (x2,y2,z2). Of course, it reflects tomograph geometry.
How should I transform this data into 3D sinogram, say, my_projection, in order to use correctly tomopy.recon() function, in particular with Astra FBP implementation, i.e.

Can you say a little more about your specific data structure? Are you saying your data is a list of values as a 1D array with each point matching a separate (x1,y1,z1) and (x2,y2,z2)?

**Comment by rshopa** [comment]
dgursoy, thank you for the explanation.

The data is stored in a file as a 6-column table (not data frame) with ~150,000 rows, each corresponding to one LOR (line-of-response). Columns represent x1 y1 y1 x2 y2 z2 coordinates (indices 1 and 2 correspond to hit-points of gamma-quanta at tomograph detectors). 
The axis are consistent with PET geometry, i.e. x^2 + y^2 = R^2 (R - tomograph radius), z - axial position.

btw, the sinogram dimensions depend of angle discretization, so I suspect it must be 180x128x184 or 180x128x128 for the 180 projections. As I understood, `pad` selects axis of rotation - x or z for True or False, respectively.

**Comment by dgursoy** [comment]
Then you have 150,000x6 array for specifying the acquisition geometry, and another 150,000x1 array for corresponding measurements, correct?  So the question is how this 150,000 rows are organized? I can figure it out if you can pass me your geometry and data files (not necessarily the full data, but a smaller one for me to understand the structure of the geometry)

> btw, the sinogram dimensions depend of angle discretization, so I suspect it must be 180x128x184 or 180x128x128 for the 180 projections.

Correct!

**Comment by dgursoy** [comment]
I think I understand how your data is formatted, but if rows are random hit points then we can't put it in a structured 3D sinogram. Once you can provide me the data, I can write you a specialized 3D reconstruction algorithm for your input based on CPUs, and make it available for PET-like data. As a side note, I think MLEM type algorithms can better cope with PET/SPECT type measurements. Just let me know how you'd like to proceed.

**Comment by rshopa** [comment]
I have a task to apply merely 3D FBP (supposedly for NEMA norms calculation).
I just wanted to understand the format of 3D projection for `tomopy.recon()` usage and whether it could be applied to my data.
The data could be transformed to structured table or dataframe, I did it earlier for 2D case in R, which package, unfortnately, hasn't got a 3D FBP implementation.

**Comment by rshopa** [comment]
@dgursoy , it looks like I managed to transform my lost of LORs (line-of-response) into some data frame and create a reconstructed image.
I would like to ask about resolution of reconstruction.

TomoPy probably hasn't employed the same transform algorithm which I had seen in other implementations. For example, one of the form in R: 
```
iradon(rData, XSamples, YSamples, mode = "FB")
```
where `XSamples` and `Ysamples` are the dimensions of the reconstructed image (number of samples on the x(y)-axis). They change amount of pixels, preserving the geometrical dimensions.

I've noticed that `num_gridx` and `num_gridy` parameters in `tomopy.recon()`  function just change the span of XY axis and not the resolution. It reconstructs a smaller or larger portion of the image but does not change the scaling of the data (sic!)

From the [theory](http://slideplayer.com/slide/4707854/)

s like I managed to transform my lost of LORs (line-of-response) into some data frame and create a reconstructed image.
I would like to ask about resolution of reconstruction.

TomoPy probably hasn't employed the same transform algorithm which I had seen in other implementations. For example, one of the form in R: 
```
iradon(rData, XSamples, YSamples, mode = "FB")
```
where `XSamples` and `Ysamples` are the dimensions of the reconstructed image (number of samples on the x(y)-axis). They change amount of pixels, preserving the geometrical dimensions.

I've noticed that `num_gridx` and `num_gridy` parameters in `tomopy.recon()`  function just change the span of XY axis and not the resolution. It reconstructs a smaller or larger portion of the image but does not change the scaling of the data (sic!)

From the [theory](http://slideplayer.com/slide/4707854/) (the formula at the bottom of the first slide), it is obvious that one could set an arbitrary discretization angle *Delta.theta* in order to perceive higher resolution.

But how could it be changed in TomoPy?
