### ISSUE TITLE
Post-processing with tomopy

### ISSUE THREAD

**Issue by SebastianArmin** [tomopy/tomopy#193]
Dear tomopy developers,

I am a student in University of Hamburg and we are doing computer tomography with the help of tomopy. Normally we just use tomopy to reconstruct the 3D images but now we want to go further and do some post--processing like Zernike phase contrast ，or some filters to do the segmentation. So we want to ask if tomopy has these functions inside?

Another question is for visualization the results. Usually we use FIJI to visualize the results but sometimes it is the pain in the ass to switch to another software, so have you added some function in tomopy so that we can visualize the results?

Thanks in advance
Yours Sebastian

Mathematical department, University of Hamburg

**Comment by dgursoy** [comment]
Hi @SebastianArmin! 

We also don't have any segmentation module, and won't have one unless the segmentation problem will be posed as an integral part of the tomographic reconstruction problem (i.e. input data are sinogram and output data are segmented volumes). The place for segmentation algorithms that are independent of tomography is scikit-image, and we can use from there once needed.

But.. We'd be more than happy to include your tomography-related algorithms in tomopy, e.g. Zernike phase contrast, etc. We don't have anything currently that can do that. 

Tomopy is currently a library for tomographic processing algorithms and we haven't planned (and probably will never have plans) for adding anything related to visualization. Because most of the time tomography outputs a structured grid and the visualization part can be handled by all other Python software from matplotlib to vispy, etc. I am typically fine with imageJ but I am mostly working with 2D images, but @lbluque is working on some 3D visualization tool for tomography. He can give you a better answer.

**Comment by SebastianArmin** [comment]
Hi Dgursoy

OK, cool, thanks for your answers. I will try to work on the segmentation part and see if I can get some result.

Have a good day!
