### ISSUE TITLE
Gridrec and FBP results are off from expected

### ISSUE THREAD

**Issue by lbluque** [tomopy/tomopy#209]
We tested the tomopy recon algorithms with a phantom, and are not getting the expected results for pixel intensity values for gridrec and FBP (all other algorithms agree with what we expect). Gridrec pixel intensity values are off by a factor of approximately 1/2, and the FBP values are off by several orders of magnitude.

**Comment by michael-sutherland** [comment]
See issue #132.  It appears something broke when I updated gridrec to use fftw.

**Comment by dgursoy** [comment]
I suspect this is because of the filter weights. They need to be x2.

**Comment by michael-sutherland** [comment]
But is that something I changed?

**Comment by lbluque** [comment]
I don't think so @michael-sutherland. 
This probably came in with the `filter_par` keyword feature.

**Comment by dmpelt** [comment]
I did a bit of testing on this, and the problem already exists at b780c846326c65f682038e3400b61e2a23429718 (April 2015). So it is definitely not something caused by the FFTW inclusion. 

I also suspect it is related to the filter definition. I will compare with astra's filter definitions, and see whether I can find out what is going on.

**Comment by dmpelt** [comment]
I create PR #216 that makes the gridrec filter definitions closer to astra's definitions. There indeed seemed to be a factor of two missing in some cases, so after the change this issue seems to be fixed.
