### ISSUE TITLE
find_center_vo() complaining about negative values

### ISSUE THREAD

**Issue by skylarjhdownes** [tomopy/tomopy#224]
I'm attempting to use the find_center_vo() function to get the center of rotation for some data.  
When I run the function on my stack of projections without any optional values it gives the error "ValueError: negative dimensions are not allowed.".  

The same error is shown when I test the function using the sinogram.npy test data.  It makes it through the search_coarse() function, but gets hung up in search_fine() -> create_mask() with Ncol = -201.  

I'm not sure precisely what this algorithm is expecting for input.  My data doesn't have a full 180 degrees of projections so it makes sense that I'd get something odd from it, but I'm surprised that the test sinogram isn't working.  Could anyone shed some light on what could be going on?

**Comment by dgursoy** [comment]
What is your data.shape?

**Comment by nghia-vo** [comment]
Hi, as Doga just asked, this can help to track the issue which may be caused the downsample function.

**Comment by skylarjhdownes** [comment]
The shape of the sinogram.npy test data is (45, 1, 91).  The shape of my data is (1, 512, 2048).

**Comment by skylarjhdownes** [comment]
The sinogram.npy test data is not being manipulated by the downsample function in this case, the data is not large enough to enter the if _tomo_shape[0] * _tomo_shape[1] > 4e6: block.

**Comment by skylarjhdownes** [comment]
def test_find_center_vo():
    sim = read_file('sinogram.npy')
    cen = find_center_vo(sim)
#    assert_allclose(cen, 45.28, rtol=1e-2)

This is the test I'm running that throws the error.  It's basically the same as test_find_center().

**Comment by nghia-vo** [comment]
Yeap, that causes problem because the next command doesn't handle for the case of not using downsample. 
---------------------------------------------
# Fine search for finding the rotation center.
    fine_cen = _search_fine(_tomo, srad, step, init_cen*4, ratio, drop)
    logger.debug('Rotation center search finished: %i', fine_cen)
------------------------------
If you could modify the code on your computer you should update the command like this:
------------------------------------------------------------
if _tomo.shape[0] * _tomo.shape[1] > 4e6:  # If data is large (>2kx2k)
          fine_cen = _search_fine(_tomo, srad, step, init_cen*4, ratio, drop)
else:
          fine_cen = _search_fine(_tomo, srad, step, init_cen, ratio, drop)
-----------------------------------------
The error is "init_cen*4". This should be applied only for the case of using downsample.  I hope Doga will fix this error soon.

**Comment by nghia-vo** [comment]
Yeap, that causes problem because the next command doesn't handle for the case of not using downsample. 
---------------------------------------------
# Fine search for finding the rotation center.
    fine_cen = _search_fine(_tomo, srad, step, init_cen*4, ratio, ### drop)
    logger.debug('Rotation center search finished: %i', fine_cen)
------------------------------
If you could modify the code on your computer you should update the command like this:
------------------------------------------------------------
if _tomo.shape[0] * _tomo.shape[1] > 4e6:  # If data is large (>2kx2k)
          fine_cen = _search_fine(_tomo, srad, step, init_cen*4, ratio, drop)
else:
          fine_cen = _search_fine(_tomo, srad, step, init_cen, ratio, drop)
-----------------------------------------
The error is "init_cen*4". This should be applied only for the case of using downsample.  I hope Doga will fix this error soon.

**Comment by skylarjhdownes** [comment]
That change makes the test react as I expected.  Thanks for your help.

**Comment by dgursoy** [comment]
Thanks for catching this.
