### ISSUE TITLE
need padding option in remove_stripe_ti

### ISSUE THREAD

**Issue by xianghuix** [tomopy/tomopy#254]
remove_stripe_ti gives less artifacts in many cases than remove_stripe_fw. However, current remove_stripe_ti does not have padding option so it introduces cyclic convolution artifacts especially when the object size is close to the camera field of view. It would be nice to add padding option in remove_stripe_ti.

**Comment by ydeno** [comment]
this discussion is  on very high level, so I am thinking to leave it... I dont know now....

**Comment by nghia-vo** [comment]
Did you use the option of nblock>1? There're artifacts if you divide a sinogram to many chunk of rows (or blocks) as implemented in remove_stripe_ti. 
regularization-based methods works on real space so the padding is often not necessary (padding is critical for Fourier-based or Wavelet-based methods which is to reduce the boundary effect).

**Comment by xianghuix** [comment]
With remove_stripe_ti you can see dark circular zone in the reconstructed slice images. This seems like some boundary effects in filtering (in both real and Fourier spaces). I can artificially pad the data before remove_stripe_ti and see reduced artifacts in the sample area. I wonder if there is better way to remove/reduce such non-uniform background artifacts.

________________________________

**Comment by nghia-vo** [comment]
These artifacts ("bonus" rings) caused by high contrast features (edges) of the sample (which are enhanced more by Fresnel diffraction of coherent source). Real-space methods basing on summation of the intensity along each sinogram column to detect rings. If there're high contrast features on the way, they will indicate wrong rings -> apply correction on the wrong rings -> give bonus rings. To reduce these kinds of artifacts, you can put sample closer to the camera to reduce the impact of coherent source (if users don't need phase contrast).  In term of image processing, you can apply threshold filter (or similar things) to get rid of high contrast edges (high frequency features) before use summation of the sinogram column.

**Comment by xianghuix** [comment]
With padding on image width dimension I can reduce the nonuniform background.
________________________________

**Comment by nghia-vo** [comment]
Could you send me by-email that sinogram? I'll give it a try without padding. Cheers

**Comment by nghia-vo** [comment]
I know what you mean now. The ticket title was misleading :-). This issue caused by the Fourier transform in the reconstruction step, not by the ring removal (real-space method) itself.  It happens when sample bigger than field of view, edge padding is the best way to deal with it. Padding works well for FBP but not for gridrec 
![compared](https://cloud.githubusercontent.com/assets/12136997/24544801/95540e30-15fc-11e7-93f1-4703fb72b03a.png).

**Comment by xianghuix** [comment]
Thanks for looking into this. I used gridrec for reconstruction. The sample size is actually smaller than the field of view. I tried both remove_stripe_fw and remove_stripe_ti. With remove_stripe_fw (padding option is True), I don't have bowling background effect. With remove_stripe_ti I however have the background issue. This makes me think the issue is related to padding. Indeed padding helps to reduce that.
________________________________

**Comment by nghia-vo** [comment]
Honestly, I hardly see the point of using padding for real-space method, and the use of padding on the width of the image even make it more confusing. Could you please share one sinogram of that data? Then we can clarify what going on. Cheers
