### ISSUE TITLE
I have problem with installation on python 3.6

### ISSUE THREAD

**Issue by ydeno** [tomopy/tomopy#261]
linux@SERV01:~$ conda install -c dgursoy tomopy
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - tomopy -> dxfile -> python 3.5* -> openssl 1.0.1*
  - tomopy -> dxfile -> python 3.5* -> xz 5.0.5
Use "conda info <package>" to see the dependencies for each package.

**Comment by tacaswell** [comment]
Do tomopy and friends have conda-forge recipes yet?

**Comment by dgursoy** [comment]
We set it up a while ago, but, not sure if different builds for Pythons are tested.

**Comment by tacaswell** [comment]
It probably just need to be re-rendered https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock

**Comment by dmpelt** [comment]
I started the process of updating the feedstocks, but it might take a few days to get everything set up correctly (for example, dxchange has already been updated but fails to build since the dependencies have not been updated yet). See https://github.com/conda-forge/edffile-feedstock/issues/5 , https://github.com/conda-forge/dxchange-feedstock/issues/2, https://github.com/conda-forge/spefile-feedstock/pull/3, and https://github.com/conda-forge/dxfile-feedstock/pull/1 for the current status. After these have been correctly built, we can update the feedstock for tomopy. Would it be a good idea to update to a more recent commit at the same time by creating a new release with a version number?

**Comment by BexNeko** [comment]
This problem still exists, is there a fix yet?

**Comment by ZeliangSu** [comment]
I have the same problem

**Comment by dgursoy** [comment]
@dmpelt any plans on updating the feedstocks? It seems the troublemaker is the edffile.

**Comment by dmpelt** [comment]
I hadn't looked at this after creating the pull requests. I don't think anything happened with the `edffile` feedstock, but it looks like you figured out how to fix it? If so, thanks!
