### ISSUE TITLE
Windows 10 - distribute wheels

### ISSUE THREAD

**Issue by thejinx0r** [tomopy/tomopy#301]
This should be more of a discussion than a real issue.

I added tomopy to AppVeyor which is the Windows CI ( #299 ).
Assuming ( #300 ) gets resolved quickly, we should be able to generate python wheels for Windows users.

My question / discussion point is: how should the wheels be distributed?

- The precompiled binaries can't be distributed through conda-forge since it doesn't support gcc for windows (aka mingw or msys2).

- We could do releases on PyPI, but I have no experience with it and I don't know if it's a good idea or not.

This issue relates to:
#283 #271

**Comment by dgursoy** [comment]
Is there a workaround for the first item? There is a long thread here about a similar subject:
https://github.com/conda-forge/conda-forge.github.io/issues/112

We can set up a separate distribution just for Windows (first I can think of is PyPI), but I don't think it will be easier to support in the long run. I'd really want to see if we can find a way to make it conda-forge compatible.

**Comment by thejinx0r** [comment]
It could be possible.
I can check it out in the new year. I don't think I will have time to flesh this idea out until then.

**Comment by jasonthiese** [comment]
Do you still plan to make a tomopy wheel for Windows?  I have tried installing from source, so far without success, in both python 2 and 3.  The Visual C++ compiler that works with python 2 apparently doesn't support C99, so that failed.  (The exact error message:  "...\tomopy\src\utils.h(50) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory".)  I'm still waiting for the compiler that works with python 3 to be installed -- where I work, one cannot simply install software oneself.

**Comment by thejinx0r** [comment]
I'm pretty sure there is a way to download the binaries from the ci builds.

I accidentally wiped my windows partition on my laptop and can't test the
build system anymore.
