### ISSUE TITLE
downsample() Segmentation fault

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#304]
The [downsample](https://tomopy.readthedocs.io/en/latest/api/tomopy.misc.morph.html#tomopy.misc.morph.downsample) function gives a segmentation fault when trying to down sample large arrays:

`ndata = np.ones((1800, 1200, 1920), dtype="float32") `
`print(ndata.shape)`
`ndata1 = tomopy.downsample(ndata, level=4, axis=1)`

gives

`(1800, 1200, 1920)`
`Segmentation fault`

**Comment by carterbox** [comment]
The reason is that `1800 * 1200 * 1900 > MAXINT32`, so when `c_downsample` gets to the higher indices of the output array, the index rolls over to the negative integers. This leads to attempted illegal access of memory.

Fixes
-----
- Use [`unsigned` or `unsigned long`](https://en.wikipedia.org/wiki/C_data_types) instead of `int` for indexing arrays to expand maximum indexing range
- There will always be some theoretical limit on the max supported array size, so raise an error or use assertion to inform the user when the volume of the output or input arrays is greater than `MAXINT`.

**Comment by carterbox** [comment]
I suggest that the maximum supported array size should be the `numpy` maximum array size; whatever what is.

**Comment by dgursoy** [comment]
Thanks @carterbox for the fix!
