### ISSUE TITLE
can't install ver. 1.1.3

### ISSUE THREAD

**Issue by maximka48** [tomopy/tomopy#317]
Hello!

I try to install the new version 1.1.3. From conda and pip it's not possible as only 1.1.2 is available.
From the source with setup.py I have the following mistake. Could you please advise me what to do. I have all the dependencies installed (incl. mkl 2018.0.2) and up-do-date (at least by conda).

running build_ext
building 'tomopy.libtomopy' extension
gcc -pthread -B /home/maxim/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_MKL -I/home/maxim/anaconda3/include/python3.5m -c src/utils.c -o build/temp.linux-x86_64-3.5/src/utils.o -std=c99
gcc -pthread -B /home/maxim/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_MKL -I/home/maxim/anaconda3/include/python3.5m -c src/project.c -o build/temp.linux-x86_64-3.5/src/project.o -std=c99
gcc -pthread -B /home/maxim/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_MKL -I/home/maxim/anaconda3/include/python3.5m -c src/gridrec.c -o build/temp.linux-x86_64-3.5/src/gridrec.o -std=c99
src/gridrec.c:56:21: fatal error: mkl.h: No such file or directory
     #include "mkl.h"
                     ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by dgursoy** [comment]
Hi @maximka48 - we're waiting for another patch before we make a release on Conda (possibly next week). 

For getting the mkl headers you can should install ```mkl-devel```, which is available in conda.

**Comment by maximka48** [comment]
@dgursoy Didn't help, the same error. But ok, I will wait for conda release.

I also moved today from 1.0.2 ver to 1.1.2 and noticed that tomopy.recon with 'gridrec' algorithm kills the kernel with this error: anaconda3/lib/python3.5/site‑packages/mkl_fft/../../../libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

The code is the same and worked this morning with the old version of tomopy.

**Comment by carterbox** [comment]
Hi @maximka48,

```
src/gridrec.c:56:21: fatal error: mkl.h: No such file or directory
```
Is an error from `gcc` which states that it cannot find the `mkl` header file it needs to compile the c extensions of `tomopy`. You will need to add the location of your `mkl` header file to the `C_INCLUDE_PATH` by setting an environmental variable or changing line 30 of `setup.py`. 

https://github.com/tomopy/tomopy/blob/29949bee02a1b620c6af247faded01cffa3d336f/setup.py#L28-L30

If you installed `mkl-devel` using conda, the header files should be located in the `foo/conda/include` directory where `foo` is the install location of conda on your computer. By default this folder is your Home directory.

In my case, I would change line 30 to `C_INCLUDE_PATH = ['/home/carterbox/intel/intelpython3/include']` because I'm using `intelpython3` instead of the standard `anaconda3`.
