### ISSUE TITLE
Cross-platform complex types for gridrec

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#379]
When gridrec was [updated to use FFTW around 4 years ago](https://github.com/tomopy/tomopy/commit/fcf3389be0a9ad846f13857d846fffdc71da44cc), a custom complex struct was replaced with complex types defined in <complex.h>. This unfortunately means it cannot be compiled by MSVC because MSVC doesn't implement <complex.h>.

How can we implement a complex type that is cross-platform such that libtomopy can be compiled by MSVC instead of MinGW?

[Related](https://github.com/tomopy/tomopy/pull/375#issuecomment-445360906).

**Comment by carterbox** [comment]
https://stackoverflow.com/a/31948016/4459405

**Comment by newville** [comment]
@carterbox  Yes, the problem of lack of support for C99 complex in MSVC was mentioned (see #310) as part of the motivation for using MinGW to get tomopy to compile and link on Windows. 

I haven't seen or heard about problems using gridrec on Windows using MinGW.   I've used it for quite a few reconstructions.  Are you or other people seeing problems with it?

You have emphasized that you expect people to use Anaconda Python and conda-forge and want to support Windows. MinGW is supported by Anaconda Python on Windows and works to build tomopy.   
Is it too obvious to use MinGW?

**Comment by carterbox** [comment]
I assumed that using MSVC would be better because it is the compiler used to compile CPython, and it is the native compiler for Windows. This assumption may be wrong. :man_shrugging:

We may not be using any of the features that MSVC has that would make it a better choice than MinGW, and as you mentioned, we have not had any compatibility issues with libraries that were compiled with MSVC.

**Comment by dgursoy** [comment]
I get that both seem to be OK for our applications. But then I’d stick with MinGW unless there is any strong against argument, because some power users like @newville is more comfortable with it. Some more general discussion on this:
https://stackoverflow.com/questions/8029092/gcc-worth-using-on-windows-to-replace-msvc

I’d check runtime performances of both because this is the number one item in priority. 

Also @tekinbicer is developing code with C++11 that we want to be merged. Any comments on this thread @tekinbicer?

**Comment by tekinbicer** [comment]
> I get that both seem to be OK for our applications. But then I’d stick with MinGW unless there is any strong against argument, because some power users like @newville can be more comfortable with it.
IMHO, it would be better to stick with MinGW if it works.
 
> Some more general discussion on this:
> https://stackoverflow.com/questions/8029092/gcc-worth-using-on-windows-to-replace-msvc
> 
> I’d check runtime performances of both because this is the number one item in priority.
That's a valid point. If the performance is an issue, then the code probably be refactored with macros. Still, before moving MSVC it might be worth trying other windows compatible compilers (clang?)
 
> Also @tekinbicer is developing code with C++11 that we want to merge at some point. Any comments on this thread @tekinbicer?
C++11 has complex types, so using C++11 should solve the problem. My codebase has iterative reconstruction algorithms, but we can consider adding gridrec. 
We can/should merge my code base to tomopy. The main reason why this hasn't happened is that it has dependencies to other libraries, e.g. parallel hdf5 and mpi, which need to be cleaned up. The code also needs documentation. We should plan this.

**Comment by carterbox** [comment]
@tekinbicer I also noticed that MSVC has implemented <complex> for C++11. However, my understanding is that[ `ctypes` is not compatible with C++](http://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#id3), so in order to switch to C++11 we need to change our interface.

**Comment by newville** [comment]
@carterbox @dgursoy @tekinbicer   To be clear, I do not advocate for MinGW instead of Microsoft (or any other) compilers for any reason except that we got that to work.  If someone figures out how to use a different compiler, and it works, that would be fine with me. 

I am not sure about how MKL deals with this. It appears that MKL_FFT also uses `float Complex`. It's kind of hard to believe that MKL_FFT does not work with MSVC and requires Intel compilers oe C++. Maybe looking at the MKL_FFT examples would give some clues?

I don't think that `ctypes` prevents the use of C++ in the code, just that the interface exposed to Python needs to be C compatible.  For tomopy, I think that should not be too hard, as (I believe) the current interface is mostly *functions* that pass arrays in and out and do not retain state between calls.  You can definitely use more complex structures, though I would not suggest trying to map C++ objects, and I think you cannot overload function signatures.  At worst you might have some specialized "extern C" functions.

**Comment by jrmadsen** [comment]
> I don't think that ctypes prevents the use of C++ in the code, just that the interface exposed to Python needs to be C compatible

@newville is correct. I do this in the gpu-devel branch of my fork and it uses C++11.

**Comment by jrmadsen** [comment]
Just for additional information, PyBind11 is the best package I have found for binding C++ to Python (I use it in the PyCTest and TiMemory packages). It is basically a C++11 header-only version of Boost.Python without any external dependencies. I looked into using it for TomoPy but it seemed like too much work to migrate and provided little in return. But if y'all are interested in C++ and Python in the future for other projects, it has built-in mappings from Python data-types to C++ STL types and also a C++ interface for numpy arrays. And I know it works for Windows as well as UNIX because PyCTest and TiMemory both support Windows.

**Comment by carterbox** [comment]
But actually, the conda-forge feedstock environment is probably the same build environment as one we are using which means MinGW 7.2 should still be available. I'll investigate.

**Comment by jrmadsen** [comment]
Well I think the point of using C++11 is that we would then be able to use `std::complex<float>` and thereby use the MSVS compilers.

**Comment by jrmadsen** [comment]
Ah I found this: https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=vs-2017
I think MSVS compilers for complex will work if you include `<tgmath.h>` instead of `<complex.h>`. It is not entirely clear

**Comment by carterbox** [comment]
Good news! The Anaconda `defaults` channel offers GCC 5.3. The package name is `m2w64-gcc`. If we use that package instead of the `mingw` package, then CMake passes the std_c11 tests.

For right now, it seems best to use `m2w64-gcc` for the Windows compiler because:

- It is available from default anaconda channels (important for conda-forge distribution)
- It supports C11 (important for @jrmadsen 's work)
- It doesn't require refactoring of gridrec.c (saves development time)

Thanks for the feedback and ideas, everyone. One thing I'll have to do is:
- [ ] Get CMake to choose `m2w64-gcc` as the compiler inside the conda build environment instead of MSVC using [conda compiler tools](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#).

**Comment by jrmadsen** [comment]
C++ std::complex is supported in 1.5.x and is enabled on Windows + MSVC due to OpenCV linking issue with MinGW bc conda doesn't provide a compatible library for the compiler.
