### ISSUE TITLE
Idle3 cant process  normalize_roi/noralize_bg

### ISSUE THREAD

**Issue by lex62lex** [tomopy/tomopy#393]
Hi, I'm new to tomopy and am currently using it for reconstruction of gas jets, creating a density profile.
My data is not as nice as it could be, as I'm doing the phase extraction with the neutrino toolkit.
I would like to utilize the normalize_bg function to normalize my data set into something that doesn't produce a vague ring at the end of the gridrec method. My difficulties are with using it, as soon as its in the code idle stops and asks if i want to kill the process or if i would like to cancel. Is there a way to make Idle wait for this (to me) unknown sub process to finish?

`proj = dxchange.reader.read_tiff_stack(fname,ind)`

`proj = tomopy.normalize_bg(proj)`

**Comment by decarlof** [comment]
@lex62lex can you give us access to the tiff files?

**Comment by lex62lex** [comment]
I uploaded them here in my Google drive.
The neutrino toolkit that i am currently using saves the images in a PNG, that I then grayscale and save as TIFF. The resulting images have a phantom field (a lighter coloration in the empty space) that i would like to get rid of. This data set is not perfect, but a preliminary one, that I wanted to start with.

https://drive.google.com/open?id=1BHSdICP5TG5qL1Xl1QjgKWajlUDGEb0_

**Comment by dgursoy** [comment]
Do you collect images with no object for normalization? 

What are the corresponding rotation angles for each image?

**Comment by decarlof** [comment]
@lex62lex The images do not open correctly with ImageJ (it seems there is a corrupted metadata regarding byte order, data type or something else). Can you please confirm how the tiff files were generated?

**Comment by decarlof** [comment]
@lex62lex I think the issue is in the byte order. Your tiffs are compressed with  **FillOrder: msb-to-lsb**, full settings are:

TIFF Directory at offset 0xb31e (45854)
  Image Width: 912 Image Length: 342
  Resolution: 72, 72 pixels/inch
  Bits/Sample: 8
  Compression Scheme: AdobeDeflate
  Photometric Interpretation: min-is-black
  **FillOrder: msb-to-lsb**
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 342
  Planar Configuration: single image plane
  Page Number: 0-1
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
  Predictor: horizontal differencing 2 (0x2)

Are you generating these with some Adobe application on Windows?

**Comment by dgursoy** [comment]
@lex62lex is this resolved?

**Comment by lex62lex** [comment]
Sorry it took me a while to get back to this. The problem was idle3. Somewhere in the command stop was used and this automatically stopped the process. Running this directly in the environment made this work perfectly
