### ISSUE TITLE
Can apply tompy  for Microwave imaging? How images are formed from scattering parameters? 

### ISSUE THREAD

**Issue by namjoo** [tomopy/tomopy#397]
I see ART and SART algorithms that work with Microwave Tomography.

**Comment by carterbox** [comment]
In theory, yes. Although TomoPy was developed X-rays in mind; microwaves are just photons of a different energy. However, it depends on how you are using the microwaves. The TomoPy reconstruction algorithms are developed for transmission and emission tomography.

* In transmission tomography, we measure the decrease in flux across the sample, and the images are formed from the absorption properties of the specimen.
* In emission tomography, we measure photons that are emitted due to interactions with the beam, and the images are formed from the florescence properties of the specimen.

In these cases, strongly scattering materials are bad because they are not included in our reconstruction models.

However, you can use these algorithms for any measurement process that can be expressed as a linear integral across the specimen.

**Comment by dgursoy** [comment]
It'll not work with microwave imaging because the forward model of x-ray imaging is quite different than microwave imaging. We model wave-matter interaction with line integrals because there is not multiple scattering events with x-rays. They simply are attenuated on their straight path as they pass through. With microwaves, the forward model requires solution of partial differential equations or other techniques for modeling wave propagation in a much more dispersive media. So, while the underlying optimization techniques can be similar (ART, SIRT, etc.), the forward and inverse problems that we try to solve are often quite different.
