### ISSUE TITLE
Ring Removal after reconstruction

### ISSUE THREAD

**Issue by ankitaeclipse** [tomopy/tomopy#415]
Hi,

I am looking to remove ring artefacts from my reconstructed micro-CT images. Is it possible to do this using the remove stripe functionality in tomopy or is it restricted to during reconstruction process?

Thank you for your time.

Kind Regards,
Ankita Singh

**Comment by carterbox** [comment]
Hi @ankitaeclipse,

The post-reconstruction ring removal function we have is here:
https://tomopy.readthedocs.io/en/latest/api/tomopy.misc.corr.html#tomopy.misc.corr.remove_ring

**Comment by ankitaeclipse** [comment]
Hi @carterbox,

Thank you for posting the link. 

1) The function requires some threshold parameters: thresh, thresh_max, thresh_min. How are these parameters decided?
2) What should be the quantization level of the reconstructed image that is given as an input to the function? 

Kind Regards,
Ankita

**Comment by decarlof** [comment]
remove stripe work on the sinogram => is applied before the recontruction

**Comment by ankitaeclipse** [comment]
Hi @decarlof 

Thank you for letting me know. 

I just want to clarify: https://tomopy.readthedocs.io/en/latest/api/tomopy.misc.corr.html#tomopy.misc.corr.remove_ring

refers to ring removal before reconstruction?

**Comment by carterbox** [comment]
The one ring removal method we have is for removing rings post-reconstruction. That is what you initially asked for. Stripe removal methods that @decarlof is suggesting take a sinogram as input. They are used before reconstruction.

1. The rings that you see in your reconstructed image have some brightness value. The thresholds are used to tell the algorithm in what value range to look for the rings, so it doesn't correct things that are not rings.

2. It looks like this function takes floating point valued images, so you can use any bit-depth you want.

**Comment by decarlof** [comment]
no  https://tomopy.readthedocs.io/en/latest/api/tomopy.misc.corr.html#tomopy.misc.corr.remove_ring

works on the reconstructed images

**Comment by ankitaeclipse** [comment]
Thank you @decarlof and @carterbox for your feedback. I will give this a try and get back to you on how I go.

**Comment by ankitaeclipse** [comment]
Hi @carterbox  @decarlof 

I tried the tomopy.misc.corr.remove_ring function. I get the following error:

![Ring Removal Error](https://user-images.githubusercontent.com/17406040/58931215-311dd080-87a2-11e9-96fe-8b2f1753242e.JPG)

**Comment by carterbox** [comment]
`out` cannot be `True`. According to the docs:

> out (ndarray, optional) – Output array for result. If same as arr, process will be done in-place.

It must be an array the same shape as `rec` or `None`.

**Comment by ankitaeclipse** [comment]
Thank you @carterbox. 

In one of your previous comments, you mentioned that "The rings that you see in your reconstructed image have some brightness value. The thresholds are used to tell the algorithm in what value range to look for the rings, so it doesn't correct things that are not rings."

Is there an assumption that the rings have a brightness that is significantly different from that of other features in the image? 

What if the rings look something like this. Please see attached.

Thank you for your patience and time in answering the questions.

Ankita
![Ring Removal](https://user-images.githubusercontent.com/17406040/58998506-68dd5480-8844-11e9-9dcd-86b64be24112.JPG)

**Comment by ankitaeclipse** [comment]
Here's what it looks like after ring removal.

![After Ring Removal](https://user-images.githubusercontent.com/17406040/58998884-65e36380-8846-11e9-9a5f-fbc8a3d07780.JPG)

**Comment by dyparkinson** [comment]
In the first image you sent, the rings are relatively subtle (compared to some images I've seen!), and there is not extreme contrast difference between the phases, so probably multiple different ring removal algorithms would work fine on that image. In the second image you posted, it covers a larger area and there is a very bright spot near the bottom right. With some ring removal algorithms (take fourier wavelet for example), I would expect the ring removal algorithm would actually lead to dark shadows on the sides of the bright spot (and if you had very dark spots, FW ring removal might create lighter shadows). For remove_ring to work in these cases, you set the max threshold to be just below the bright spot pixel value, and in that case it should reduce or eliminate the shadowing (for the min threshold, set it just above the dark spots). If you're not getting this kind of shadowing, then this ring removal algorithm may not be the optimal one to use, as it often introduces strong artifacts at the center of the image. Also, if the bright spot is similar in pixel value to what the rings are, you will have a problem because it will not remove those rings.

This repo  https://github.com/lbluque/ring-removal-jtblair I think is the same or very close to the code that used in the tomopy implementation, and lists the paper from Prell et al that describes the method (we should probably add that paper in the tomopy references...)

**Comment by dgursoy** [comment]
@ankitaeclipse I would give [this](https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.stripe.html#tomopy.prep.stripe.remove_stripe_ti) a try. The rings in your reconstruction seems to be mild and [Eduardo et al. method](https://scripts.iucr.org/cgi-bin/paper?pp5053) may be a better choice.

**Comment by ankitaeclipse** [comment]
@dyparkinson thank you for explaining this to me and @dgursoy thank you for pointing me to the papers. In my research team, we have always had a problem with ring artefacts, with no solution for it really. I thought there would be 'the one' ring artifact removal algorithm that could be applicable to all. 

I will give those a try and see how I go. Is there a general rule of thumb that helps you decide which ring removal algorithm you would use for a particular case? or is it more like reading papers and understanding which ring removal methods suit your case?

**Comment by nghia-vo** [comment]
@ankitaeclipse : your data is cone-beam or parallel-beam? If it's parallel-beam, there're many options to clean them from the sinogram space.  You can try this [paper](https://doi.org/10.1364/OE.26.028396)  where I classified types of rings and methods to clean each of them (implemented in [tomopy](https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.stripe.html#tomopy.prep.stripe.remove_all_stripe)). Unfortunately, there's no "the one" can deal with all types of ring artifacts. Each method has its own advantages and disadvantages. However, we can combine them to tackle different types of rings.

If your data is cone-beam where reconstruction is done directly without sinogram generation, you can try this easy method: convert your reconstructed image to the polar coordinate, use [wavelet-fft](https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.stripe.html#tomopy.prep.stripe.remove_stripe_fw) to clean them, then convert back to the normal coordinate. Note that the others in tomopy.stripe won't work well and can strongly affect the quality of the reconstructed image because they are based on some assumptions only valid in the sinogram space.

**Comment by ankitaeclipse** [comment]
@nghia-vo thank you for writing all that and referring me to your paper. I now understand why some/most of my ring removal algorithms didn't work very well. They weren't suited for my type of data. I will look into the method using wavelet-fft you suggested to work with my data [my case is of a cone-beam].

**Comment by nghia-vo** [comment]
@ankitaeclipse : I've tried stripe removal methods on cone-beam data and it works pretty well. To do that you generate a 2D image combining each row of every projections (called sinogram in parallel-beam). Apply stripe removal method to this image (try remove_all_stripe method). Do the same for all sinograms. Then apply FDK on this data to get reconstruction images. The disadvantage of this approach is that the reconstructed image may be a bit blurry due to the cone-beam effect. But it may  help you to clean noise.  I recommend to use non-FFT-based stripe removal approaches to avoid making reconstructed images more blurry.

**Comment by CTPassion** [comment]
> @ankitaeclipse : I've tried stripe removal methods on cone-beam data and it works pretty well. To do that you generate a 2D image combining each row of every projections (called sinogram in parallel-beam). Apply stripe removal method to this image (try remove_all_stripe method). Do the same for all sinograms. Then apply FDK on this data to get reconstruction images. The disadvantage of this approach is that the reconstructed image may be a bit blurry due to the cone-beam effect. But it may help you to clean noise. I recommend to use non-FFT-based stripe removal approaches to avoid making reconstructed images more blurry.

Was just trying this and got my cone beam data into sinograms.  How do i know what I should put in the require parameters for all_stripe? Plus I get this error when I try anyway:

`NameError: name '_rs_algorithm_6' is not defined`

**Comment by nghia-vo** [comment]
I fixed this bug a while a go, issue 426 [https://github.com/tomopy/tomopy/issues/426](url). Update the latest version of tomopy and try again.

**Comment by nghia-vo** [comment]
Some examples used here: https://github.com/nghia-vo/sarepy/blob/master/examples/examples.py
for a sinogram size around 2k x 2k. Basically the parameters relate to the size of the defective area. The snr parameter controls the strength of the detection algorithm, smaller is more sensitive. Snr= 3 works for most of the case. Have a look to the [paper](https://doi.org/10.1364/OE.26.028396) which explains things in more details.
