### ISSUE TITLE
Recon acceleration in v1.5.0

### ISSUE THREAD

**Issue by jdgelb** [tomopy/tomopy#416]
Very excited to see the new recon_accelerated routine in v1.5.0! However, I'm trying to get Tomopy_peri to build (which appears to be the acceleration engine of choice?), but the package is a little difficult for me to build... apparently it requires Intel Parallel Studio, which looks to be commercial software (and I'm guessing only required to enable the Xeon Phi acceleration). 

Are there other GPU engines that I might consider trying in lieu of Tomopy_peri? Or can somebody give me a tip or two on how to get Tomopy_peri to build / handshake with Tomopy without having to buy a commercial package? 
(hacking peri to remove all the Xeon Phi code comes to mind, since I only really want the Nvidia GPU routine... why accelerate with a measly 70 cores when 4000 are just a cool G away? :-) )

**Comment by jrmadsen** [comment]
The new accelerated routines in TomoPy built into TomoPy and are implemented with CUDA. I'm not familiar with tomopy_peri but if you've got the nvcc compiler or clang-6+ (which is also a CUDA compiler) just built TomoPy from scratch and the build system will pick up working CUDA compiler if it is in your path. Tested on Windows and Linux. Pass `accelerated=true` as an argument to `tomopy.recon` for either the mlem or sirt algorithms

**Comment by jrmadsen** [comment]
*the new accelerated routines _are_ built into TomoPy

**Comment by jeffgelb-sg** [comment]
Ah, thanks for that! I'll give it a try then with the regular tomopy.recon call. (I was confusing myself looking at the recon_accelerated routine)

**Comment by jrmadsen** [comment]
So I just took a look at that other repo. You are going to get much better performance out of the built-in TomoPy. That package mostly just implements the CPU algorithm on the GPU (which I myself also tried) whereas the new method built into TomoPy takes an alternative approach to the problem which structures the data in a far more optimal layout for GPUs.

**Comment by dgursoy** [comment]
The acceleration wrapper was built through an SBIR collaboration and intended for implementation of penalized maximum likelihood algorithm on Intel Xeon Phis and Nvidia GPUs. But because Intel announced the KNL discontinuance last year and having more GPU implementations in the package, maybe we can think about editing this wrapper in the future versions. @dakefeng do you have any update to share?

**Comment by jeffgelb-sg** [comment]
Thanks for the feedback! I was looking in entirely the wrong place. I'm giving the accelerated reconstruction a try today and I can't seem to get it to recognize the presence of my GPU. I get this in the output:

```
==========================================================================================
Available GPU options:
	INDEX  	KEY           DESCRIPTION                             
	    0  	cpu           Run on CPU (OpenCV)                     	(default)

To select an option for runtime, set 'device' parameter to an INDEX or KEY above
==========================================================================================

------------------------------------------------------------------------------------------
Selected device: 	    0  	cpu           Run on CPU (OpenCV)                     
------------------------------------------------------------------------------------------


[0] Initialized tasking run manager with 32 threads...
[0]> cxx_sirt : nitr = 100, dy = 1024, dt = 361, dx = 1024, nx = 1024, ny = 1024
[0]> sirt_cpu : nitr = 100, dy = 1024, dt = 361, dx = 1024, nx = 1024, ny = 1024
```
Is there something else I need to do to get the GPU recognized? I installed the cudatoolkit package but it didn't seem to make a difference (tested on both Windows and Linux with NVIDIA GPUs).

**Comment by carterbox** [comment]
You will need to build TomoPy from source on your local machine in order to have the CUDA accelerated functions enabled. This is because our build infrastructure currently does not have NVCC available, so we cannot distribute the CUDA enabled version over conda. As such, you will also need to install the cudatoolkit using the NVidia installer because there is no conda package which includes NVCC. Let me know if you need help installing.

**Comment by jdgelb** [comment]
Ok, thanks for that! It will probably take me some time before I can get to compiling myself from source, but I'll update here if/when I can do that. 

Out of curiosity, how does the GPU acceleration work when leveraging the ASTRA libraries? I've been able to use that GPU accelerated version of SIRT and it works nicely via Conda installations... are they including nvcc?

**Comment by carterbox** [comment]
ASTRA is a separate project. They have their own channel and build infrastructure. We use the conda-forge build infrastructure.

**Comment by jdgelb** [comment]
Ok so I got TomoPy built from source and am now rocking a fresh build of v1.5.2 from a git clone today. The GPU keeps running out of memory... is there a way I can estimate how much memory it needs? I was trying to reconstruct a 1k x 1k dataset with 721 views on a Geforce 1080Ti (which has 11 GB of memory)... here's the full output below:
`Performing SIRT reconstruction with 100 iterations...
Reconstructing 1 slice groups with 1 master threads...
Detected 1 CUDA capable devices

Device 0: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          10.2 / 10.1
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11264 MBytes (11811160064 bytes)
  GPU Max Clock rate:                            1582 MHz (1.58 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Multiprocessor count:                          28
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 175 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >




==========================================================================================
Available GPU options:
        INDEX   KEY           DESCRIPTION
            0   cpu           Run on CPU (OpenCV)
            1   gpu           Run on GPU (CUDA NPP)                     (default)

To select an option for runtime, set 'device' parameter to an INDEX or KEY above
==========================================================================================

------------------------------------------------------------------------------------------
Selected device:            1   gpu           Run on GPU (CUDA NPP)
------------------------------------------------------------------------------------------


[0] Initialized tasking run manager with 64 threads...
[0]> cxx_sirt : nitr = 100, dy = 1024, dt = 901, dx = 1024, nx = 1024, ny = 1024
[0]> sirt_cuda : nitr = 100, dy = 1024, dt = 901, dx = 1024, nx = 1024, ny = 1024
[0] Running on device 0...
cudaCheckError() failed at gpu_malloc@'c:\users\sigray\downloads\tomopy\source\include\utils.hh':309 : out of memory
cudaCheckError() failed at gpu_malloc@'c:\users\sigray\downloads\tomopy\source\include\utils.hh':309 : out of memory
[TID: 0] cudaCheckError() failed at gpu_malloc@'c:\users\sigray\downloads\tomopy\source\include\utils.hh':309 : out of memory
Falling back to CPU algorithm...
[0]> ThreadPool destroyed...`

**Comment by carterbox** [comment]
There is a tool called `nvidia-smi` which will tell you how much GPU memory is being used. Try with one z slice, then use batches to prevent memory overflow. We don't have automatic memory management, sorry!

**Comment by jrmadsen** [comment]
Ah well I expect this is happening because your GPU has only 1 GB of memory and your CPU has 32 threads, this means that each thread has it's own `GpuData` instance which contains two dy x nx x ny arrays of 4-byte (float) entries:

https://github.com/tomopy/tomopy/blob/25225b7df825884253240af6be3b87db6286fffd/source/include/data.hh#L389
https://github.com/tomopy/tomopy/blob/25225b7df825884253240af6be3b87db6286fffd/source/include/data.hh#L390

So based on:
> [0]> cxx_sirt : nitr = 100, dy = 1024, dt = 901, dx = 1024, nx = 1024, ny = 1024

So in other words, each array has `1024*1024*1024 = 1073741800` entries. 
This equates to `64 * 2 * 1073741800 * 4 = 54975580000` bytes, or ~549 GB. In the standard version, this would be reduced by a factor of 64 because it is serial in the C code but that 8.6 GB would still not fit on the GPU so as @carterbox said, you need to use batches. 

If you pass `pool_size = 12` to `tomopy.recon` and reconstruct in batches of 8 slices, this should get you to about 0.8 GB on the GPU w.r.t. the thread-local array and leave a little extra room for the other arrays shared among the threads. If this still fails, reduce the pool size incrementally until it fits on the GPU but in general, the more threads, the faster it reconstructs on the GPU.

**NOTE:** the default `pool_size` parameter is calculated from `(2 * num_cores) / num_python_threads` where `num_cores` is the number of cpu cores and `num_python_threads` is `min(ncore, num_slices)` where `ncore` is the parameter in `tomopy.recon`. In general, a patch should probably be added to make sure the pool size does not exceed ~24 since beyond that, the performance actually starts to degrade.

**Comment by jdgelb** [comment]
Thanks for this explanation!! I understand much better now where the memory footprint request is coming from. I'll give this a try with splitting my volume into smaller chunks and reconstructing those individually, then stitch them back together at the end to produce the full volume. Will report back as progress is made!

**Comment by jrmadsen** [comment]
No problem. Both rec.py and phantom.py in the benchmarking directory have this capability so those might be useful as a guide.
