### ISSUE TITLE
Trouble updating dxchange

### ISSUE THREAD

**Issue by meaturner** [tomopy/tomopy#417]
I am trying to run a program and get an value error that i believe is because of the dxchange version and update to theta. However, I am still having problems updating what I believe to be the solution which is dxchange. Here is the error:

"Traceback (most recent call last):
  File "exsitu_arun.py", line 600, in <module>
    main(sys.argv[1:])
  File "exsitu_arun.py", line 564, in main
    rec_try(fname, nsino, rot_center, center_search_width, algorithm=algorithm, binning=binning)
  File "exsitu_arun.py", line 495, in rec_try
    proj, flat, dark, theta = dxchange.read_aps_32id(h5fname, sino=sino)
ValueError: need more than 3 values to unpack "

**Comment by tomopy** [comment]
dxchange is not a dependency of tomopy anymore. Please do a conda update following the instructions at

https://dxchange.readthedocs.io/en/latest/source/install.html

francesco

On Jun 5, 2019, at 11:10, meagggs <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to run a program and get an value error that i believe is because of the dxchange version and update to theta. However, I am still having problems updating what I believe to be the solution which is dxchange. Here is the error:

"Traceback (most recent call last):
File "exsitu_arun.py", line 600, in
main(sys.argv[1:])
File "exsitu_arun.py", line 564, in main
rec_try(fname, nsino, rot_center, center_search_width, algorithm=algorithm, binning=binning)
File "exsitu_arun.py", line 495, in rec_try
proj, flat, dark, theta = dxchange.read_aps_32id(h5fname, sino=sino)
ValueError: need more than 3 values to unpack "
