### ISSUE TITLE
Minimal dependencies to build tomopy for reconstruction

### ISSUE THREAD

**Issue by cryos** [tomopy/tomopy#448]
**Describe the problem**
We are looking at the best way of adding TomoPy to Tomviz.  We have a Python environment with Python 3.7, SciPy, NumPy, and have a PR to add h5py. The dependency set looked larger than expected, including OpenCV and several other components. What is the minimal set of dependencies/build configuration to support reconstruction?

**Expected behavior (if applicable)**
Ideally no big new dependencies, perhaps we need to understand how to turn off optional features.

**Helpful images (if applicable)**
Add screenshots to help explain your problem.

**Platform Information:**
 - OS: We want o support Linux, macOS, and Windows
 - Python Version 3.7
 - TomoPy Version Latest/master

**Additional context**
This is really us exploring  packaging, another approach is to use a Docker container with a miniconda starting point.

**Comment by newville** [comment]
@carterbox Hm, well OK.  I have definitely had more struggles with conda than with pip in the past couple of years.   MKL and OpenCV are on PyPI.  I have not tried building tomopy with PyPI only tooling, but I don't know why it would not work.

If I understood the original question, the Tomviz project was asking how they could include tomopy as a dependency.   I'm in the same position, and I can say that it is not super easy.  As far as I can tell, one is obliged to use `conda-forge` to get the latest version of tomopy.  That does limit packaging and distribution options.

**Comment by jrmadsen** [comment]
If you can install all the dependencies from PyPi, you can get the latest distribution and not depend on conda-forge via `git clone https://github.com/tomopy/tomopy.git tomopy-tmp && pip install ./tomopy-tmp && rm -rf ./tomopy-tmp`

**Comment by jrmadsen** [comment]
Supporting multiple distribution centers _is work_. For frameworks, APIs, etc. like MKL and OpenCV, it makes sense to support multiple distribution methods. For applications developed primarily by domain scientists (like tomopy), it is asking quite a bit of them to officially support multiple modes of distribution.

**Comment by newville** [comment]
@jrmadsen Thanks, though building from the source kit is not something I usually find challenging ;).  FWIW, using Python.org Python 3.7 on MacOS and installing `opencv-python`, `mkl`, `mkl_include` and `tifffile` I did manage to build tomopy and pass `pytest`.  I have not tried this on Windows or Linux.  Maybe "yet".  I guess if you all are committed to not pushing tomopy packages to PyPI that I might consider doing this.

As a "domain scientist" (at least in CyberInfrastructure-Speak) who develops applications and libraries that others use (some users are even outside "domain"), I do actually understand how much work it can be to package and distribute applications and libraries.  I spent a healthy portion of the past week (and maybe "decades") doing exactly that.  It turns out that over the past year, pretty much every time I try to build the conda-based kits for my largest package (which depends on many libraries), conda and tomopy are what make life most difficult. 

I think the most telling thing you said was "For *applications* developed primarily by domain scientists (like tomopy)".  I think of tomopy as a library, not as an application.  I want my apps to be able to call tomopy.  Tomopy is not driving the narrative.  I *want* to make it available to my users, because of all of the good work being done here.

I sort of expect that approach the same would be true for Tomviz.  They appear to be asking themselves "can we use tomopy within Tomviz".   I can fully appreciate that they might read the discussion here as "no".  I can also appreciate that if they (a DOE-funded project) were able to answer "yes", that might be a very good thing for tomopy.

**Comment by jrmadsen** [comment]
It wasn't my intention to suggest that you weren't familiar with the work involved in packaging/distribution. Sorry if it came across that way.

I guess I don't really consider tomopy a library because it does not support _building_ against it's headers/library like MKL, OpenCV, etc. but that I probably a skewed C/C++ viewpoint bc it does provide functionality one can build other tools from.

**Comment by dgursoy** [comment]
I think one main distinction of TomoPy from others is that there is no coordinated effort of the contributions in TomoPy. Developers are often domain scientists, who develop a piece of code for a specific function, and we simply capture these independent efforts in TomoPy through PRs. This means that the package is not developed by few individuals, who have more control on these kind of choices. Also because the control on the development process is loose, the dependencies will always tend to grow.

A good way to deal with this situation would be providing a ```minimimal``` build for TomoPy in addition to the ```complete``` version, as @carterbox said above. But still it is hard to draw the line what is minimal and what is not, because it depends on the imaging technique and hard to find a common denominator. 

@newville: are you having problems because not all the packages that you provide to the users are available in ```conda-forge```? If this is the case I think you want to have more control on the resolution of the dependency issues, is this the reason?

**Comment by newville** [comment]
@jrmadsen Hm, tomopy *is* a library just like MKL and OpenCV, and it supports building against its headers/library (well, its defined interface and the implementation of that, anyway). Just like in Java, the "import" statement replaces C's "include" to mean use the API from a *library*.   In fact, tomopy is *only* a library. There is no main() entry point and all users are expected to write code that has "import tomopy".

@doga: well, not all of the packages I use are on `conda-forge`, but I that is not my goal. I don't want to have to use `conda-forge` or any other third-party channel anyway.    Like many others, I have a conda channel that I use for my app, where I *know* those versions work well together. 

From my perspective, PyPI is just better.  Wheels are easy enough to create (`python setup.py bdist_wheel`) and upload to PyPI (`twine upload dist/tomopy***.whl`). It doesn't seem like much of a burden to me...  But if you don't want to do this, and if I ever figure out getting OpenCV and CMake to work together so that I can reliably build on all platforms, I would happily push tomopy wheels to PyPI.

**Comment by cryos** [comment]
I think the idea of a minimal and a complete build would be very useful. I don't want to place too much burden on the tomopy team, and there are other paths for us to work on such as using a miniconda-based Docker image in our workflows. I think that tomopy is a Python library, and that is how we want to use it. Anything we can do to make the packaging simpler when not all features are needed would be useful to us, and hopefully the wider community.

**Comment by dreycenfoiles** [comment]
@jrmadsen I am currently in the process of breaking up extern.py into submodules and I noticed LIB_PTL is declared, but not used anywhere in the code. I was wondering what its purpose was?
