### ISSUE TITLE
Adding CUDA to CMake languages

### ISSUE THREAD

**Issue by jakirkham** [tomopy/tomopy#451]
**Is your feature request related to a problem? Please describe.**

The new standard with CMake CUDA support is to add CUDA as a project language. IIUC this is not being used in this project currently. Would be good to switch to CUDA as a project language to avoid issues with legacy CMake CUDA support.

**Describe the solution you would like.**

Should result in adding [CUDA to this line]( https://github.com/tomopy/tomopy/blob/193151fd5ddb35f4523d975b12cf448a6b55c2fe/CMakeLists.txt#L27 ) if I'm not mistaken.

**Describe alternatives you've considered.**

There is still the legacy CUDA support in CMake, which the project already uses (again if I'm not mistaken), but users are encouraged to move away from it.

**Additional context.**

Here's a [blogpost by one of the CMake developers about this]( https://devblogs.nvidia.com/building-cuda-applications-cmake/ ).

**Comment by jrmadsen** [comment]
TomoPy uses the modern version of CUDA and CMake. You cannot add CUDA to the first line bc that would make it such that a CUDA compiler would be required, which it isn't. CUDA is optional. If you look through the CMake, you'll find the language is enabled later. Your compiler issues are likely something lower level like your C++ compiler isn't supported by NVCC under the hood

**Comment by jakirkham** [comment]
That's great to hear! Thanks for letting me know. 🙂

Where does this get set exactly?

**Comment by carterbox** [comment]
We use both the `find_package` and `enable_language` commands in this file.

https://github.com/tomopy/tomopy/blob/193151fd5ddb35f4523d975b12cf448a6b55c2fe/cmake/Modules/Options.cmake#L25-L37

Maybe we should be using [check_language](https://cmake.org/cmake/help/v3.12/module/CheckLanguage.html#module:CheckLanguage) instead of `find_package` because CUDA is was upgraded from package to full-language? Not sure it matters?

**Comment by jakirkham** [comment]
Well it kind of does because both `find_package` (the old way of configuring CUDA support) and `enable_language` (the new way of configuring CUDA support) are being used at the same time. Seems like this would cause some surprising behavior as they are not intended to be enabled at the same time as each other. Switching to `check_language` seems like a good idea.

**Comment by jrmadsen** [comment]
A find package just sets local and cache variables and some macros/functions. Some of those cache variables are also set by the enable language. There is no conflict when using the find package to set the cache variables, the issues arise from using the macros and functions to build CUDA targets, and that is not done. The system for both being used is bc, at the time, simply doing the check and enable language was spuriously causing issues by the internal core language support for CUDA was not setting/finding the NPP library. Thus, I added the find package bc it found the NPP libraries. If this issue no longer exists in more recent CMake versions, get rid of the find package. 

If adding CUDA to the project statement fixes things for you, I will again tell you that the issue is not with our CMake, it is an issue with your C++ compiler. If all three are in the project statement, CMake will change the C++ compiler to a compatible version bc it knows it needs to activate CUDA. But bc CUDA is optional, we can't do that and by the time you get to the CUDA part of CMake, your C++ compiler is set to an incompatible version and the compiler is fixed at that point so CMake cannot activate the CUDA compiler.

**Comment by jakirkham** [comment]
Should this still be open?

**Comment by carterbox** [comment]
Yes. The bot was supposed to wait until Monday to close this issue.

**Comment by jrmadsen** [comment]
as I noted previously, CUDA is already enabled as a language, just not explicitly bc you can compile tomopy without CUDA. This ticket should be closed.
