### ISSUE TITLE
Center of rotation correction - algorithmic details

### ISSUE THREAD

**Issue by PaulVoland** [tomopy/tomopy#456]
Dear TomoPy team,

I am currently working with the ASTRA toolbox for my master thesis at the University of Stuttgart at the chair of continuum mechanics of Holger Steeb. Since there is a need to correct center of rotation misalignments, I tried out the coupling of TomoPy with the ASTRA toolbox, which works quite good to find the horizontal misalignment value. Since we want to use the 3D reconstruction algorithms (FDK) or at least 2D fan beam geometries with suitable reconstruction algorithms, I am interested in the way you correct the misalignment. In the end, a solution to correct the misalignment in the MATLAB environment would be desirable to us.

Am I correct that all reconstruction algorithms available in TomoPy or also in the coupled version with ASTRA are for a parallel beam setup?

And also I wasn't able to find the source file where the correction is actually done - can you help me with this (I used a conda environment to run TomoPy, dxchange and ASTRA altogether)?

If you have some hints for literature, I would also be very grateful.

Thanks in advance and with the best wishes from Stuttgart,
Paul Voland

**Comment by carterbox** [comment]
Hi @PaulVoland,

I can't help you with MATLAB things because we don't currently provide MATLAB bindings to our compiled code. However, I can answer all of your questions:

- Yes, all the reconstruction algorithms that are callable through `tomopy.recon()` are for parallel beam only.
- We have [documentation](https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.alignment.html) for our entire API; there is a link from the documentation to the source code for every function.
-  I assume that you are asking about `tomopy.align_seq()` and `tomopy.align_joint()`? The publication about these articles is [here](https://doi.org/10.1038/s41598-017-12141-9).

**Comment by dgursoy** [comment]
Also I believe you can set-up ASTRA for cone-beam reconstruction and call it from TomoPy. You need to set the geometry as you wish and pass these options as a dictionary.
```
options = {'proj_type': 'linear', 'method': 'FBP', ...}
recon = tomopy.recon(proj, theta, algorithm=tomopy.astra, options=options)
```

**Comment by PaulVoland** [comment]
Thanks for your quick answers!

I'm not quite sure if your answers perfectly fit to my problem in the following sense:

You answered the first question with a yes (only parallel beam reconstruction algorithms) @carterbox (which was also my understanding of TomoPy up to now). I just tried out to pass some options like
`recon = tomopy.recon(stack, theta, center=rot_center, sinogram_order=True, algorithm=tomopy.astra,
	options={'method':'SIRT', 'proj_type':'line_fanflat', 'num_iter':25})`
following the answer of @dgursoy with data that worked fine until changing the `'proj_type'` to `'line_fanflat'`(the ASTRA projector for a fan beam setting with the line method, see ASTRA API). I got a `Configuration Error in FanFlatBeamLineKernelProjector2D: Unsupported projection geometry` error. This is we I assume also from ASTRA the only algorithm/projector combinations that will work are the ones for parallel beam.

I already saw that the center variable is passed to `tomopy.recon`, where it is passed further to `_dist_recon(tomo, center, recon, algorithm, args, kwargs, ncore, nchunk)` and from there to `algorithm(tomo[slc], center[slc], recon[slc], *args, **kwargs)`... So my actual problem is to find the location in the code where we really calculate something with the center argument (also if using the `tomopy.find_center` or `tomopy.write_center` methods, they only call the `tomopy.recon` routine once again).

I also couldn't find a link between the reconstruction algorithm and the aligning methods you referenced (but I didn't read the paper right now, I will do this tomorrow).

Of course I don't expect you to give me any kinds of help for my MATLAB coding, the thing I'm interested in is the mathematics you use in your code to correct the center of rotation misalignments in the projection data (before reconstructing?!)...

**Comment by dgursoy** [comment]
Are you trying to find the find the center of rotation or are you trying to align the projection images with respect to each other assuming that each one is distorted independently? Because the former is easy and you need to find one single scalar value. But the latter is harder and requires knowing alignment parameters for each projection image.

No I don't think we have a limitation on calling different ASTRA geometries. Please try the ```extra_options``` key for setting up the geometry options:
```
options={'method':'SIRT', 'num_iter':25,  'proj_type':'linear',  'extra_options':{'MinConstraint':0}}
```
I don't have much experience in fan/cone-beam geometries. @dmpelt Do you know the right options to set for fan-beam geometry in ASTRA?

**Comment by PaulVoland** [comment]
I'm rather interested in the "calculation mechanism" of correcting one single projection at a given angle with a known/given/algorithm-estimated center of rotation (misalignment) than in finding the location. In a first step, I would like to perform a correction for a fan beam setup (with flat detector). Let's assume we have a rotation axis which is perfectly vertically aligned (parallel to the z-axis), but translated only in x-direction by some pixels in the resulting projection image for a fixed angle. How would you prepare the projection data to remove the influence of this misalignment (which yields blurred edges)? Of course you can also assume we have the sinogram data for a fixed height h (in z-direction) for a full 360° µCt scan - just how you need the data...

I can't see by now if we are talking about the latter scenario, I would be glad to understand the correction mechanism for one z-slice for the start.

In a second step, one could try to interpolate the COR misalignment scalar value over the total height to include the 3D effect of cone beam, for instance by taking z-slices at different heights and use an array of CORs for each slice afterwards. But this isn't the topic by now.

And the code snippet you added didn't change anything for me. I still doubt that TomoPy uses fan beam since usually you have to give some information about the source to object respectively the object to detector distance to describe the fan effect, which is not the case here, in contrast to ASTRA running solely in MATLAB for other projectors and algorithms.

**Comment by dgursoy** [comment]
Often, you don't touch the projection images. The reconstruction algorithm "back-projects" these images to the corresponding object pixels based on the rotation center. 

However, it is also fine if you want to pre-process by either padding or cropping the projection images based on the known rotation center such that the rotation center comes to the middle of the projection image. 

And finally, if all these shifts are random for each angle, then check [here](https://doi.org/10.1038/s41598-017-12141-9) and the references therein.

**Comment by carterbox** [comment]
> No I don't think we have a limitation on calling different ASTRA geometries. Please try the `extra_options` key for setting up the geometry options:

@dgursoy  is mistaken. Our wrapper of ASTRA does not allow non-parallel projection geometries. The wrapping code is found here:
https://github.com/tomopy/tomopy/blob/58b8b2d324a6d27dfa9954ee073a9044c2f87695/source/tomopy/recon/wrappers.py#L187-L188
and as you can see, the projection geometry is hard coded and inaccessible to the user through the `tomopy.recon()` interface.

The correct way to accomplish using a non-parallel-geometry-ASTRA-function call with the `tomopy.align_seq()` would be to create a mini-wrapper of ASTRA Python API using [`functools.partial()`](https://docs.python.org/3/library/functools.html#functools.partial) from the standard library. You can pass your mini-wrapper function to `tomopy.align_seq()` as long as it has a function signature which is the same as all of the other TomoPy reconstruction functions. In other words, it must have the following function signature `astra(tomo, center, recon, theta, **kwargs)`.

**Comment by nghia-vo** [comment]
@PaulVoland : So you would like to find center of rotation of a cone-beam tomographic data. The methods of calculating [center of rotation](https://tomopy.readthedocs.io/en/latest/api/tomopy.recon.rotation.html) in Tomopy are for parallel-beam. To use them, you need to convert your data (1 slice) from a fan-beam sinogram to a parallel-beam sinogram. The fan-beam sinogram can be used is the slice at the same z-position of the X-ray source referred to the projection image (If your cone beam system is well-aligned it should be at the middle of the projection image). 
If the converted sinogram is 360-degree sinogram (mostly is the case for cone-beam tomography to reduce cone-beam artifacts), to use "find_center_vo" you need to drop half of this sinogram because this method works on 180-degree sinogram.
To use "find_center_pc" you separate this sinogram into two halves, then flip the second half from left to right.  
No pre-processing step is needed if you use "find_center".
The function of converting from [fan-beam to parallel-beam](https://tomopy.readthedocs.io/en/latest/api/tomopy.sim.project.html#tomopy.sim.project.fan_to_para) is not implemented yet in Tomopy, so would be great if you can implement it and contribute back.
