### ISSUE TITLE
Cone Beam Geometry : Astra

### ISSUE THREAD

**Issue by rockandsalt** [tomopy/tomopy#493]
**Is your feature request related to a problem? Please describe.**
I would like to know if adding cone geometry is possible to the Astra wrapper?

**Describe the solution you would like.**
Is me adding `'geometry'` to the[ astra dictionnary](https://github.com/tomopy/tomopy/blob/79bf70d24faa0fb20544c6320c08ea64ea0a5c12/source/tomopy/recon/wrappers.py#L72) and replacing the hard-coded `parallel` with a [opt['geometry']](https://github.com/tomopy/tomopy/blob/79bf70d24faa0fb20544c6320c08ea64ea0a5c12/source/tomopy/recon/wrappers.py#L183) be an acceptable solution?

**Comment by carterbox** [comment]
Hi @rockandsalt, 3D cone geometry is incompatible with TomoPy's parallelism model; we slice the projections along the vertical dimension because we assume that the light path has no vertical component. Thus, adding the 2D fan geometry might be trivial, but 3D would require additional changes.

I would welcome a pull request updating or improving our wrapper of ASTRA; it is within the scope of this project, I think. However, the current maintainers of this project all work at synchrotrons, so we cannot spend time developing new features that would not be used at these facilities.

**Comment by rockandsalt** [comment]
Hi @carterbox,
thanks for the response. I was trying to modify the code. But I have issues with installing Astra. The astra toolboox downgrades the numpy version which breaks the tomopy installation. Is there anyway around that?

**Comment by carterbox** [comment]
You must use `astra-toolbox>1.8` because they changed their API and didn't want to update their old releases with newer NumPy versions.
