### ISSUE TITLE
Qt 5.12.9 dependency

### ISSUE THREAD

**Issue by jdgelb** [tomopy/tomopy#518]
I am noticing that TomoPy (through the conda installation on Windows 10) requires Qt, which it pulls from conda-forge. The problem is that Anaconda is stuck on an old version of Qt, which is missing some nice rendering features that started in 5.13. I am wondering if this Qt dependency is truly necessary for tomopy or if I can "safely" force-remove it? I would like to install Pyside2 from PIP, which will come bundled with a more up-to-date Qt.

**Comment by carterbox** [comment]
Hi @jdgelb,

TomoPy does not require Qt; it has no graphics rendering capabilities or official GUI.

```
$ conda search --info tomopy --platform win-64

tomopy 1.7.1 py37h79cbd7a_100
-----------------------------
file name   : tomopy-1.7.1-py37h79cbd7a_100.tar.bz2
name        : tomopy
version     : 1.7.1
build       : py37h79cbd7a_100
build number: 100
size        : 3.2 MB
license     : BSD 3-Clause
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/tomopy-1.7.1-py37h79cbd7a_100.tar.bz2
md5         : b40133a67671ced131ec8ea9fba9b01f
timestamp   : 2020-02-19 19:59:49 UTC
constraints : 
  - astra-toolbox >1.8
  - python_abi * *_cp37m
dependencies: 
  - libopencv >=4.2,<4.3.0a0
  - libopencv >=4.2.0,<4.2.1.0a0
  - mkl >=2020.0,<2021.0a0
  - mkl_fft
  - numexpr
  - numpy >1.12
  - python >=3.7,<3.8.0a0
  - pywavelets
  - scikit-image
  - scipy
  - six
  - tifffile
  - vc >=14,<15.0a0

```
It looks like Qt is a dependency of `libopencv`. However, our summer intern removed our forced dependencies on OpenCV and MKL, so you can self-build tomopy without this dependency (or build TomoPy+OpenCV without Qt). I haven't been able to publish a build without OpenCV yet because of some difficulty with the conda-forge pinnings.

Resolved by: https://github.com/conda-forge/tomopy-feedstock/pull/36.

**Comment by jdgelb** [comment]
Thanks for the explanation! Just for kicks I did try force-removing the Qt package and that did indeed break things, so I'm back on 5.12.9 for the time being. If it's just a matter of being patient for 1.8.0 to hit conda-forge, I'm ok to wait for that!

**Comment by prjemian** [comment]
Be aware that Qt has some non-GUI modules.
