### ISSUE TITLE
Question: the unit of voxel value 

### ISSUE THREAD

**Issue by Shamimeh** [tomopy/tomopy#544]
**Describe the problem**
We have used Tomopy library to reconstruct SPECT images. The input are projections in which the voxel values represent the number of photon detection (number of counts, int value). Also, when reconstructed with a clinical software implementing OSEM algorithm the voxels of the output have the same unit. But the output images of Tomopy have a value with a different unit (float value). I would be thankful if I can get your guidance on one or two of the following issues:

- What is the voxel unit of the output image from Tomopy?
- Due to the image reconstruction process by Tomopy, is it possible to convert the voxel value of the output image from Tomopy to the number of photon detection? If yes how?

**Expected behavior (if applicable)**
The voxel values of the output image from Tomopy indicate the number of photon detections.

**Platform Information:**
 - OS: Windows 10
 - Python Version: 3.8.5
 - TomoPy Version: 1.9.1

**Comment by carterbox** [comment]
> But the output images of Tomopy have a value with a different unit (float value). 

"Floating point" is a data type not a unit of measure. A change from integer to floating point indicates a change in precision not a unit change. TomoPy uses floating point numbers because it is more precise when computing sums across the grid for the Radon transform.

> What is the voxel unit of the output image from Tomopy?

It depends. The units of a voxel on a reconstructed grid are arbitrary. The projection data (which you provide) to perform the reconstruction should be equivalent to a sum across the grid as described by the [Radon transform](https://en.wikipedia.org/wiki/Radon_transform). Then the units of a voxel are whatever is summed to created the projections.

My 5-minute reading of the single-photon emission computed tomography Wikipedia page leads be to believe that the units of your reconstructed image should be "expected number of photon emissions per unit time" and the units of your projections are the "number of photons counted on the detector per unit time". Both are numbers of photons, but the former is a probabilistic and the later is an actual number observed.

**Comment by carterbox** [comment]
> I should mention that in our case the voxel values represent "number of photons detected" (also called counts) and it was not normalized by time

If the exposure time for the detector is the same for all views, then you have implicitly normalized by 1 unit of time. If it is not the same time for all views, then you will get an incorrect reconstruction.

> unit ??

As I already stated above, I believe the units for SPECT are "expected number of photon emissions per unit time"

> Is there any normalization during reconstruction, or using Tomopy is there any possibility to get the output value of Tomopy close to range of reconstructed image by clinical software?

I believe the result from our implementation of OSEM is appropriately scaled to match our Radon transform. i.e. applying `tomopy.project()` to the reconstructed data should approximately equal the experimentally collected projection. As you know, one of the advantages of TomoPy is that it is open source, so you can see exactly how our result is computed. Proprietary software generally is not open-source, so I will not speculate on what exactly is being done to your data to provide a different result or how to make them match. I can only tell you how our results are computed (which I have done).
