### ISSUE TITLE
Tomopy GUI

### ISSUE THREAD

**Issue by samwelborn** [tomopy/tomopy#575]
Hello,

I developed this UI so that users at SSRL can align their data and reconstruct without getting into the weeds of reading documentation. In its current state, it creates the following dashboards:

1. User information/data upload dashboard:
![image](https://user-images.githubusercontent.com/55868530/145604304-230baa1b-8a49-4e06-8a26-3e9d125c8c6f.png)
![image](https://user-images.githubusercontent.com/55868530/145604370-bdc9d34b-133b-408d-bcfc-db4e35b7285c.png)

2. Alignment dashboard:
![image](https://user-images.githubusercontent.com/55868530/145604720-1346b623-b6e3-42c7-9787-138b9a79c076.png)
![image](https://user-images.githubusercontent.com/55868530/145604747-75aa9f43-00d0-41b4-96ab-0436d4232da4.png)
![image](https://user-images.githubusercontent.com/55868530/145604791-ddeb70ae-4281-4622-96ab-e0625584cdfd.png)

3. Reconstruction dashboard:
![image](https://user-images.githubusercontent.com/55868530/145605021-83c577c1-c506-48a8-87a0-0fd16db6be55.png)
![image](https://user-images.githubusercontent.com/55868530/145605076-2be9044f-9880-4d48-8888-aa13c11bb640.png)
![image](https://user-images.githubusercontent.com/55868530/145605115-285ae7e7-e086-45ed-90d5-591cdfd48eec.png)

This is all done in a jupyter notebook.  Right now I am in the phase of restructuring my code/the gui a bit so the workflow is more smooth, and so people can understand what I have written. Will write documentation at some point, too.

Is this something you could add to this repo? If not, what is the most effective way to move forward? Can also meet over zoom if you would like to discuss this.

It primarily uses Astra toolbox, your wrappers, and some algorithms I have altered (see PS below) for both alignment and reconstruction. I don't think it would be terribly complex to add CPU-based algorithms to it. 

P.S. As mentioned in [#573](https://github.com/tomopy/tomopy/issues/573), I have also made the align_joint method significantly faster by batching/using astra. Sorry for the delay on responding to that one. There is more updated code [here ](https://github.com/samwelborn/tomopy/tree/tomodata-feature/source/tomopy/data) in tomoalign.py.

**Comment by carterbox** [comment]
No, a GUI is not in the scope of this repository (tomopy/tomopy).

However, could a tomopy GUI be hosted in the [tomopy organization](https://github.com/tomopy) to increase visibility? Yes.

This is not something to which I (personally) have the skills to contribute. You should discuss with @decarlof @dyparkinson.

**Comment by samwelborn** [comment]
OK, sounds good. I will add you all to my private repository. We can host in the [tomopy organization](https://github.com/tomopy) once it is more organized and improved.

**Comment by decarlof** [comment]
@samwelborn I suggest a meeting to discuss. Please include also @dyparkinson since there is an overlapping effort at his site.
From my side I developed [tomopy-gui](https://github.com/tomography/tomopy-gui) and [tomopy-ij](https://github.com/decarlof/tomopy-ij). Both of them did not end up being used much, so I stopped maintaining them. For some reason our users prefer the [tomopy-cli](https://github.com/tomography/tomopy-cli). I am very interested in looking at your implementation and see what features are included.

**Comment by dyparkinson** [comment]
Hi @samwelborn as @decarlof says, at the Advanced Light Source microCT beamline I've been moving all of our GUI efforts over to jupyter (and compatible web-based) things for the past year or so. Sorry I don't have a public repo for any of my work, but I'd love to meet and show you what I have and share ideas. Some of your interfaces look pretty slick, and I'll be very curious to hear about how you tested and chose which technologies to use for images/widgets. My users have been more enthusiastic about GUI's than what @decarlof has seen. Not sure why that is, but it might be due to details of implementation of command line things vs jupyter/gui things and how refined each of them is and how well we can train users in them.

**Comment by samwelborn** [comment]
Hey @dyparkinson and @decarlof - this all sounds great. I added you both to my private repository. We can continue our discussion there. 

We could integrate our ideas, especially if they overlap.
