### ISSUE TITLE
Quick questions - MLEM and CUDA

### ISSUE THREAD

**Issue by swelborn** [tomopy/tomopy#579]
1. Does MLEM require data scaled in a certain way? My results keep coming up with 0s everywhere in the reconstruction.
2. Is the EM_CUDA method equivalent to the implementation in TomoPy? For [TomoPyUI](https://tomopyui.readthedocs.org/), I do not want people to have to build tomopy -- you have to build from source to use your CUDA-accelerated algorithms right?

Thanks for your help.

**Comment by samwelborn** [comment]
I believe I solved these issues after some trial and error. There were 2 issues:
1. I was passing a float instead of an int to the tomopy algorithm (used an ipywidgets.FloatText box instead of an ipywidgets.IntText box for the UI). This causes MLEM in tomopy to yield 0s in the reconstruction, but raises no exception that I could see... may be hidden behind my UI somehow. Do you think it would be better to default to setting any input into the num_iter argument to an int instead of a float? Can't readily find the line of code that would be changed for this.
2. I had set up my reconstruction wrapper to initialize the reconstruction to very small values. This is what is done in align_joint https://github.com/tomopy/tomopy/blob/51b58c8055428181d91913c91362f443a79ad0cd/source/tomopy/prep/alignment.py#L297 so I figured it would be fine to do for all algorithms. Turns out it behaves poorly for Astra's EM_CUDA. Not sure about tomopy.

Still wondering if the EM_CUDA implementation in Astra is the same as your mlem implementation.
