### ISSUE TITLE
Current TomoPy version 1.11 has unknown SIRT error

### ISSUE THREAD

**Issue by lipigupta** [tomopy/tomopy#581]
**Describe the problem**
1.11 raises an error when using SIRT that is not present in earlier versions. Last known version that does not raise this error is 1.10.1.

**To Reproduce (if applicable)**

`tomopy.recon(..... , algorithm = "sirt"....) `

with standard args/kwargs.

```
ModuleNotFoundError: The SIRT ACCEL algorithm is unavailable because its shared library is missing. Check CMake logs to determine if TomoPy was built with all dependencies required by this algorithm.
```
**Platform Information:**
 - TomoPy Version 1.11

**Comment by carterbox** [comment]
What platform are you using?

**Comment by carterbox** [comment]
Are you building yourself for Perlmutter or using the conda-forge build? Is Perlmutter running linux?

**Comment by carterbox** [comment]
If you install the build of tomopy *without* cuda you will definitely get this error message. I tested this conda-forge build of tomopy for linux with cuda:
```
tomopy                    1.11.0          cuda11.2py310h4b94b55_1    conda-forge
```
The GPU accelerated library is included. I don't build the CPU accelerated algorithm that uses OpenCV because it isn't very fast considering it requires the entirety of opencv to be installed.
