### ISSUE TITLE
Can't install on macOS Sonoma (M1)

### ISSUE THREAD

**Issue by csparker247** [tomopy/tomopy#628]
**Describe the problem**
When I try to install tomopy using conda on my MacBook Pro (M1), conda gives me an `UnsatisfiableError` for incompatible packages. It seemingly indicates that it can't resolve `numexpr`. However, I've also attempted to install from source and have realized that the MKL dependencies might just mean that Tomopy is not compatible with Apple Silicon. I'm posting this just to confirm my suspicions.

**To Reproduce**
```
conda create -n tomopy -c conda-forge tomopy
```

```
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==14.0=0
  - tomopy -> numexpr=2 -> __osx[version='>=10.9']

Your installed version is: 14.0
```

**Expected behavior (if applicable)**

**Platform Information:**
 - OS: macOS Sonoma (14.0)
 - Tested with Python 3.8, 3.10, 3.11
 - TomoPy Version: Whatever the latest is on conda-forge.

**Comment by carterbox** [comment]
Since MKL is an optional dependency, I don't think there is any reason that (in theory) libtomo is incompatible with the OSX-arm64 platform. You can use FFTW instead of MKL on non-x86 platforms. I don't have any Apple Silicon to test, but I'd be happy to review any patches you submit which squash any Apple Silicon specific bugs.

Whether or not TomoPy's dependencies all support the OSX-arm64 platform is another question that I cannot answer. You can request the conda-forge bots to begin a [package migration](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds) for tomopy to osx-arm.

**Comment by csparker247** [comment]
Thanks for the info! I rarely use conda, and I've definitely never interacted with creating package for it, so this could be a slow adventure.  Anyway, I've at least opened a migration PR for conda-forge and I guess we'll see what happens: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5084

For both local and conda builds, I'm a little confused about where one specifies using FFTW vs. MKL. There's the env files in this repo, but also I'm not sure how that interacts with the Tomopy feedstock. Any guidance there would be appreciated.

**Comment by carterbox** [comment]
Our CMake options are [kind of hidden](https://github.com/tomopy/tomopy/blob/32b64972b89b926015b6b47c121a8d63a6f47ae9/cmake/Modules/Options.cmake#L79). Using FFTW is equivalent to `TOMOPY_USE_MKL:BOOL=OFF`

**Comment by carterbox** [comment]
libtomo does not compile for OSX ARM because there are compile errors in the PTL Submodule. These compatability errors may or may not be fixed in the latest version of PTL, but as mentioned, I have no apple silicon to test with.

I previously [worked on updating libtomo to use the latest PTL](https://github.com/tomopy/tomopy/pull/601), but that stalled when I didn't get any feedback from the author of PTL.

I would happily review either an update of TomoPy to PTL v3 if it compiles for apple silicon or a patch to the TomoPy fork of PTL which is now the submodule used in this project or a patch for both.

**Comment by csparker247** [comment]
PTL v3 compiles successfully for me with no real setup. It seems like the simplest thing would be to switch the submodule back to the original repo and see about finalizing your libtomo changes accordingly. Does the tomopy fork of PTL have anything important that would get left behind if I did this?

**Comment by carterbox** [comment]
Yeah, I'm not sure whether @LocutusOfBorg 's patches were also ported to PTL's main branch or if they were only merged into the special tomopy branch. I'm also not sure whether they would be trivially rebased onto PTL v3.

**Comment by csparker247** [comment]
It looks like a PR got opened against PTL, but it never got merged, and now the interface has changed. 

I'm currently updating your PTL update branch to compile against PTLv3 in my tomopy fork. I see two options for getting the RISC stuff back alongside the PTLv3 changes:

1) Accept that the PTL fork has diverged from upstream, merge upstream into the fork and deal with the conflicts. Use the fork going forward.

2) Update the fork to match upstream's history, then rebase/cherry pick the RISC changes on top of that as a new branch. Reopen the PR against upstream. Update all of the submodules, condos resources, etc. to point to the RISC branch until that PR gets merged. If it doesn't, rebase the RISC branch against upstream every time upstream changes. 

Option 2 seems like more work up front, but maybe easier to maintain long term.

**Comment by LocutusOfBorg** [comment]
>Yeah, I'm not sure whether @LocutusOfBorg 's patches were also ported to PTL's main branch or if they were only merged into the special tomopy branch. I'm also not sure whether they would be trivially rebased onto PTL v3.

no, they were not.
You probably also need this PR
https://github.com/jrmadsen/PTL/pull/43/files to fix macos build.

**Comment by LocutusOfBorg** [comment]
btw at the end with gcc-13, riscv64 got atomic implemented natively, so the checkatomic patches can be probably dropped (they are still useful for other architectures, but not for riscv64 at least)

**Comment by csparker247** [comment]
Can confirm that `conda install tomopy` now works on my M1 MBP!
