### ISSUE TITLE
build tomopy with Anaconda Python?

### ISSUE THREAD

**Issue by prjemian** [tomopy/tomopy#65]
Is it possible to build tomopy using Anaconda Python (from http://continuuum.io)?

**Comment by dgursoy** [comment]
I think only PyWavelets package is not included in Anaconda distributions.

**Comment by gazzar** [comment]
I did this a couple of days ago. Here is a personal build log. I've also
included my build log for dataexchange.

Gary

This is in my Linux Mint VM.

Install Python dependencies

$ conda install pillow
$ pip install PyWavelets


Install TomoPy

$ cd git-repos
$ git clone https://github.com/tomopy/tomopy
$ cd tomopy
$ sudo python install.py --boost --fftw            # Install fftw and
Boost. Get a coffee while these install.
$ export LD_LIBRARY_PATH=/usr/local/lib
$ export C_INCLUDE_PATH=/usr/local/include/boost:/usr/local/include
$ sudo python setup.py install


Append to ~/.bashrc this, or updated path if egg name changes:

# Added by me on 20150116 as part of tomopy installation
export LD_LIBRARY_PATH=~/anaconda/lib/python2.7/site-packages/tomopy-0.0.3-py2.7-linux-x86_64.egg/tomopy/lib:/usr/local/lib
export C_INCLUDE_PATH=/usr/local/include/boost:/usr/local/include

Make it so
$ source ~/.bashrc


Attempting to import tomopy now results in a glibc compatibility error.
Here are the last few lines of the traceback in my virtualbox installation,
where the user is adminuser instead of gary:

/home/adminuser/anaconda/lib/python2.7/ctypes/__init__.pyc in
__init__(self, name, mode, handle, use_errno, use_last_error)
    363
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

OSError: /home/adminuser/anaconda/bin/../lib/libm.so.6: version
`GLIBC_2.15' not found (required by /usr/local/lib/libfftw3f.so.3)


Doga found the solution to this for me a while back:

"Your source of your problem looks like an fftw import problem. Could
you try to remove the soft link which points libm.so.6→libm-2.5.so
<http://libm.so.xn--6libm-2-ek9c.5.so> in your $ANACONDA_DIR/lib.
According to some discussions in the forums this seems to be a
solution for your problem."

So

$ cd ~/anaconda/lib
$ unlink libm.so.6

import tomopy now succeeds without error!

That was the easy part. Now, if you want to build dataexchange, it gets a
little trickier. This is pretty messy, so read through it and maybe try it
yourself in a more sensible order:

# install ez_setup
$ pip install ez_setup

# install conda build environment for pyhdf
$ conda install conda-build

# pyhdf already has a build recipe
$ cd ~/git-repos/
$ git clone https://github.com/conda/conda-recipes

# build pyhdf
$ conda build pyhdf
# fails complaining can't find yacc, but it's part of bison, so
$ sudo apt-get install bison
$ conda build pyhdf
# fails complaining cannot find lex utility, but it's part of flex, so
$ conda build pyhdf
# error: couldn't find zlib library
$ sudo apt-get install zlib1g-dev
# error: couldn't find jpeg library
$ sudo apt-get install libjpeg8-dev
$ conda build pyhdf
$ conda install --use-local pyhdf

# success! upload to binstar to share the love:
$ binstar upload
/home/adminuser/anaconda/conda-bld/linux-64/pyhdf-0.8.3-np19py27_0.tar.bz2

# Apparently nor success yet, as we need netCDF4; install it
$ conda install netCDF4

# Then I think I broke h5py because import h5py caused an importerror:
# ImportError: libhdf5.so.8: cannot open shared object file: No such
file or directory
# so
$ conda update h5py

# Then build data-exchange
$ python setup.py install

# Success! Apparently.

**Comment by gazzar** [comment]
Oops, just noticed there should be a line in the dataexchange instructions:

# fails complaining cannot find lex utility, but it's part of flex, so
$ sudo apt-get install flex

**Comment by prjemian** [comment]
Thanks, that's inspiring

**Comment by tacaswell** [comment]
The issue is that the `system` packaged that is shipped with conda has a very old version of libm, you are probably using fftw (and boost) complied against your system libm which is the source of the version incompatibility.   As a stop-gap if you `conda remove system` it _should_ work.   

The real solution is to get fftw and boost built as conda packages (or at least reliable recipes for them).  I took a crack at this and had issues with the conda libm missing some functions so I suspect this might also require updating `system` (or using an old enough version of fftw?).

Getting this working is someplace on the to-do stack at BNL.

cc @celiafish @stuwilkins

**Comment by gazzar** [comment]
Hi Thomas,

Just to be clear, you're suggesting to "conda remove system" in preference
to removing the libm.so.6 symlink, right? Currently I'm not using Linux
much and I haven't run into a problem related to removing that link, but it
did concern me that it might break something. I'll probably leave the VM
unchanged for the moment and refer back to your recommendation if I need to
reinstall or if something complains about libm.so.6. Will removing the
system package break something else instead? I don't know what it's for,
nor even how to discover how it is built or where it resides.

Gary

**Comment by tacaswell** [comment]
Removing the package is more-or-less equivalent to removing the symlink (as conda installs stuff via linking when it can).  The only things that `system` links in are libm and libgfortran

```
tcaswell@eowyn:matplotlib$ cd ~/miniconda/pkgs/system-5.8-1/
tcaswell@eowyn:system-5.8-1$ ls
include  info  lib
tcaswell@eowyn:system-5.8-1$ ls -R
.:                                                                                                                                                         
include  info  lib                                                                                                                                         
                                                                                                                                                           
./include:                                                                                                                                                 
math.h                                                                                                                                                     
                                                                                                                                                           
./info:                                                                                                                                                    
files  index.json  meta  requires                                                                                                                          
                                                                                                                                                           
./lib:                                                                                                                                                     
libgfortran.so.1  libgfortran.so.1.0.0  libm-2.5.so  libm.so  libm.so.6                                                                                    
tcaswell@eowyn:system-5.8-1$                                                      
```

Tad confused where a VM came into this (I was assuming you were using conda environments).

I _think_ this is one of the packages that is just the files from a very old version of RHEL packaged up.

**Comment by gazzar** [comment]
Ah it's in pkgs. Sorry for the confusion; the VM is just a Virtualbox VM on
a Windows host. My Linux Mint OS is running inside it.

thanks,
Gary

**Comment by tacaswell** [comment]
pkgs is just where conda unpacks the tarballs too.  It then hard-links them into the installed envs.
